"""
Aşama 5 — Sprints, Backlog Items (WRICEF), Config Items
Şirket: Anadolu Gıda ve İçecek A.Ş.

3  Sprint (completed, completed, active)
28 Backlog Items (4W, 6R, 6I, 4C, 5E, 3F)
12 Config Items
"""

SPRINTS = [
    {
        "name": "Sprint 1 — Temel Konfigürasyon",
        "goal": "FI/CO, MM, SD temel konfigürasyon. Şirket kodu, tesis, depo, hesap planı tanımları.",
        "status": "completed", "start_date": "2026-01-05", "end_date": "2026-01-16",
        "capacity_points": 45, "velocity": 42, "order": 1,
    },
    {
        "name": "Sprint 2 — WRICEF Geliştirme I",
        "goal": "İlk 10 WRICEF nesnesi: e-Fatura, satınalma WF, vergi BAdI, göç şablonları.",
        "status": "completed", "start_date": "2026-01-19", "end_date": "2026-01-30",
        "capacity_points": 50, "velocity": 46, "order": 2,
    },
    {
        "name": "Sprint 3 — Entegrasyon & Test",
        "goal": "BTP arayüzleri, MES entegrasyonu, SIT hazırlık, raporlama geliştirme.",
        "status": "active", "start_date": "2026-02-02", "end_date": "2026-02-13",
        "capacity_points": 55, "velocity": None, "order": 3,
    },
]

BACKLOG_ITEMS = [
    # ── Workflows (W) ── 4 adet ─────────────────────────────────────────
    {"code": "WF-MM-001", "title": "Satınalma siparişi onay iş akışı (4 kademe)",
     "wricef_type": "workflow", "module": "MM",
     "status": "closed", "priority": "critical", "story_points": 8, "estimated_hours": 40, "actual_hours": 36,
     "complexity": "high", "assigned_to": "Elif Kara", "sprint_idx": 0,
     "description": "Tutar bazlı 4 kademeli onay: <₺25K otomatik, <₺100K bölüm müdürü, <₺500K direktör, ≥₺500K CEO.",
     "transaction_code": "ME21N", "package": "ZMM_WF",
     "acceptance_criteria": "4 seviye test edilmeli\nProxy onay çalışmalı"},
    {"code": "WF-FI-001", "title": "Fatura onay iş akışı (3 kademe)",
     "wricef_type": "workflow", "module": "FI",
     "status": "deploy", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 20,
     "complexity": "medium", "assigned_to": "Ahmet Yıldız", "sprint_idx": 1,
     "description": "Gelen tedarikçi faturası 3 kademeli onay. Tutar ve maliyet merkezi bazlı yönlendirme."},
    {"code": "WF-SD-001", "title": "Kredi limit aşımı onay iş akışı",
     "wricef_type": "workflow", "module": "SD",
     "status": "build", "priority": "medium", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Burak Şahin", "sprint_idx": 2},
    {"code": "WF-QM-001", "title": "Kalite red/kabul onay iş akışı",
     "wricef_type": "workflow", "module": "QM",
     "status": "new", "priority": "medium", "story_points": 3, "estimated_hours": 16,
     "complexity": "low", "assigned_to": ""},

    # ── Reports (R) ── 6 adet ───────────────────────────────────────────
    {"code": "RPT-FI-001", "title": "Konsolide bilanço raporu (TFRS/VUK)",
     "wricef_type": "report", "module": "FI",
     "status": "test", "priority": "critical", "story_points": 13, "estimated_hours": 64, "actual_hours": 58,
     "complexity": "very_high", "assigned_to": "Ahmet Yıldız", "sprint_idx": 1,
     "description": "Çoklu şirket kodu konsolide bilanço. TFRS ve VUK paralel. Döviz çevrimi."},
    {"code": "RPT-FI-002", "title": "Yaşlandırma raporu (müşteri/tedarikçi)",
     "wricef_type": "report", "module": "FI",
     "status": "closed", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 22,
     "complexity": "medium", "assigned_to": "Ahmet Yıldız", "sprint_idx": 0},
    {"code": "RPT-MM-001", "title": "Stok devir hızı ve raf ömrü analiz raporu",
     "wricef_type": "report", "module": "MM",
     "status": "build", "priority": "medium", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Elif Kara", "sprint_idx": 2},
    {"code": "RPT-SD-001", "title": "Satış performans dashboard (Fiori)",
     "wricef_type": "report", "module": "SD",
     "status": "design", "priority": "high", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": "Burak Şahin"},
    {"code": "RPT-PP-001", "title": "Üretim verimliliği OEE raporu",
     "wricef_type": "report", "module": "PP",
     "status": "new", "priority": "medium", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": ""},
    {"code": "RPT-FI-003", "title": "VUK uyum yasal defter raporu",
     "wricef_type": "report", "module": "FI",
     "status": "build", "priority": "critical", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": "Ahmet Yıldız", "sprint_idx": 2},

    # ── Interfaces (I) ── 6 adet ────────────────────────────────────────
    {"code": "INT-SD-001", "title": "e-Fatura / e-İrsaliye GİB arayüzü (UBL-TR)",
     "wricef_type": "interface", "module": "SD",
     "status": "test", "priority": "critical", "story_points": 13, "estimated_hours": 80, "actual_hours": 72,
     "complexity": "very_high", "assigned_to": "Zeynep Koç", "sprint_idx": 1,
     "description": "GİB e-Fatura/e-İrsaliye/e-Arşiv giden/gelen. UBL-TR 1.2. BTP CPI iFlow.",
     "transaction_code": "VF01", "package": "ZSD_EINVOICE"},
    {"code": "INT-PP-001", "title": "MES → SAP PP üretim onay arayüzü",
     "wricef_type": "interface", "module": "PP",
     "status": "build", "priority": "high", "story_points": 8, "estimated_hours": 48,
     "complexity": "high", "assigned_to": "Zeynep Koç", "sprint_idx": 2,
     "description": "MES'ten üretim onayları, hurda bildirimi. OData + BTP CPI."},
    {"code": "INT-FI-001", "title": "Banka hesap özeti (MT940/camt.053) arayüzü",
     "wricef_type": "interface", "module": "FI",
     "status": "design", "priority": "high", "story_points": 5, "estimated_hours": 32,
     "complexity": "medium", "assigned_to": "Zeynep Koç"},
    {"code": "INT-FI-002", "title": "Banka ödeme dosyası gönderim (EFT/SWIFT)",
     "wricef_type": "interface", "module": "FI",
     "status": "new", "priority": "medium", "story_points": 5, "estimated_hours": 32,
     "complexity": "medium", "assigned_to": ""},
    {"code": "INT-SD-002", "title": "EDI sipariş/sevkiyat arayüzü (EDIFACT)",
     "wricef_type": "interface", "module": "SD",
     "status": "new", "priority": "medium", "story_points": 8, "estimated_hours": 48,
     "complexity": "high", "assigned_to": ""},
    {"code": "INT-MM-001", "title": "WMS ↔ EWM stok senkronizasyon arayüzü",
     "wricef_type": "interface", "module": "MM",
     "status": "design", "priority": "high", "story_points": 8, "estimated_hours": 48,
     "complexity": "high", "assigned_to": "Gökhan Demir"},

    # ── Conversions (C) ── 4 adet ───────────────────────────────────────
    {"code": "CNV-MD-001", "title": "Müşteri ana veri göçü (15.000 kayıt)",
     "wricef_type": "conversion", "module": "SD",
     "status": "test", "priority": "critical", "story_points": 8, "estimated_hours": 48, "actual_hours": 44,
     "complexity": "high", "assigned_to": "Hakan Güneş", "sprint_idx": 1,
     "description": "ECC KNA1/KNVV → S/4 Business Partner göçü. 15K aktif müşteri + adres + iletişim."},
    {"code": "CNV-MD-002", "title": "Malzeme ana veri göçü (60.000 kayıt — gıda/ambalaj)",
     "wricef_type": "conversion", "module": "MM",
     "status": "build", "priority": "critical", "story_points": 13, "estimated_hours": 64,
     "complexity": "very_high", "assigned_to": "Hakan Güneş", "sprint_idx": 2,
     "description": "MARA/MARC/MARD → S/4 malzeme göçü. BOM, reçete, raf ömrü dahil."},
    {"code": "CNV-MD-003", "title": "Tedarikçi ana veri göçü (4.000 kayıt)",
     "wricef_type": "conversion", "module": "MM",
     "status": "design", "priority": "high", "story_points": 5, "estimated_hours": 32,
     "complexity": "medium", "assigned_to": "Hakan Güneş"},
    {"code": "CNV-FI-001", "title": "Açık kalem (AP/AR) ve stok bakiye göçü",
     "wricef_type": "conversion", "module": "FI",
     "status": "new", "priority": "high", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": ""},

    # ── Enhancements (E) ── 5 adet ──────────────────────────────────────
    {"code": "ENH-FI-001", "title": "Otomatik vergi hesaplama BAdI (KDV/ÖTV/ÖİV)",
     "wricef_type": "enhancement", "module": "FI",
     "status": "closed", "priority": "critical", "story_points": 5, "estimated_hours": 24, "actual_hours": 20,
     "complexity": "medium", "assigned_to": "Ahmet Yıldız", "sprint_idx": 0,
     "description": "KDV + ÖTV + ÖİV otomatik hesaplama. Gıda ürünlerine özel KDV %1/%10 ayrımı.",
     "transaction_code": "FB01", "package": "ZFI_TAX"},
    {"code": "ENH-SD-001", "title": "Kanal bazlı fiyatlandırma koşul tipi",
     "wricef_type": "enhancement", "module": "SD",
     "status": "deploy", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 22,
     "complexity": "medium", "assigned_to": "Burak Şahin", "sprint_idx": 1},
    {"code": "ENH-MM-001", "title": "Raf ömrü kontrolü — otomatik FIFO/FEFO",
     "wricef_type": "enhancement", "module": "MM",
     "status": "build", "priority": "high", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Elif Kara", "sprint_idx": 2},
    {"code": "ENH-PP-001", "title": "Üretim emri otomatik serbest bırakma",
     "wricef_type": "enhancement", "module": "PP",
     "status": "new", "priority": "medium", "story_points": 3, "estimated_hours": 16,
     "complexity": "low", "assigned_to": ""},
    {"code": "ENH-QM-001", "title": "HACCP kontrol noktası otomatik muayene tetikleme",
     "wricef_type": "enhancement", "module": "QM",
     "status": "design", "priority": "high", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Deniz Aydın"},

    # ── Forms (F) ── 3 adet ─────────────────────────────────────────────
    {"code": "FRM-SD-001", "title": "Sevk irsaliyesi (Adobe Form)",
     "wricef_type": "form", "module": "SD",
     "status": "closed", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 20,
     "complexity": "medium", "assigned_to": "Burak Şahin", "sprint_idx": 0,
     "description": "A4 sevk irsaliyesi. Şirket logosu, barkod, imza alanı, lot/parti bilgisi."},
    {"code": "FRM-MM-001", "title": "Satınalma siparişi formu (Adobe Form)",
     "wricef_type": "form", "module": "MM",
     "status": "test", "priority": "medium", "story_points": 3, "estimated_hours": 16, "actual_hours": 14,
     "complexity": "low", "assigned_to": "Elif Kara", "sprint_idx": 1},
    {"code": "FRM-QM-001", "title": "Kalite sertifikası / analiz raporu formu",
     "wricef_type": "form", "module": "QM",
     "status": "design", "priority": "medium", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Deniz Aydın"},
]

CONFIG_ITEMS = [
    {"code": "CFG-FI-001", "title": "Şirket kodu tanımlama (1000, 2000, 3000)",
     "module": "FI", "config_key": "SPRO > Enterprise Structure > FI > Define Company Code",
     "transaction_code": "OX02", "status": "closed", "priority": "critical", "complexity": "low",
     "estimated_hours": 4, "actual_hours": 3, "assigned_to": "Ahmet Yıldız"},
    {"code": "CFG-FI-002", "title": "Hesap planı tanımlama (CAGD — Gıda Türkiye)",
     "module": "FI", "config_key": "SPRO > FI > GL > Define Chart of Accounts",
     "transaction_code": "OB13", "status": "closed", "priority": "critical", "complexity": "medium",
     "estimated_hours": 8, "actual_hours": 7, "assigned_to": "Ahmet Yıldız"},
    {"code": "CFG-FI-003", "title": "KDV vergi kodları (%1 gıda, %10, %20, muaf)",
     "module": "FI", "config_key": "SPRO > FI > Tax > Define Tax Codes",
     "transaction_code": "FTXP", "status": "deploy", "priority": "critical", "complexity": "medium",
     "estimated_hours": 6, "actual_hours": 5, "assigned_to": "Ahmet Yıldız"},
    {"code": "CFG-MM-001", "title": "Satınalma organizasyonu ve depo tanımlama",
     "module": "MM", "config_key": "SPRO > Enterprise Structure > MM > Purchasing Org",
     "transaction_code": "OX08", "status": "closed", "priority": "high", "complexity": "low",
     "estimated_hours": 2, "actual_hours": 2, "assigned_to": "Elif Kara"},
    {"code": "CFG-MM-002", "title": "Malzeme türü (ZRAW, ZFRT, ZVER, ZAMB)",
     "module": "MM", "config_key": "SPRO > MM > Master Data > Material Types",
     "transaction_code": "OMS2", "status": "test", "priority": "high", "complexity": "medium",
     "estimated_hours": 8, "actual_hours": 7, "assigned_to": "Elif Kara"},
    {"code": "CFG-SD-001", "title": "Satış organizasyonu ve dağıtım kanalı",
     "module": "SD", "config_key": "SPRO > Enterprise Structure > SD > Sales Org",
     "transaction_code": "OVX5", "status": "closed", "priority": "high", "complexity": "low",
     "estimated_hours": 4, "actual_hours": 3, "assigned_to": "Burak Şahin"},
    {"code": "CFG-SD-002", "title": "Fiyatlandırma prosedürü (ZPRC01 — gıda)",
     "module": "SD", "config_key": "SPRO > SD > Pricing > Define Pricing Procedure",
     "transaction_code": "V/08", "status": "build", "priority": "critical", "complexity": "high",
     "estimated_hours": 16, "assigned_to": "Burak Şahin"},
    {"code": "CFG-PP-001", "title": "Üretim emri tipi (ZPP1 proses, ZPP2 diskret)",
     "module": "PP", "config_key": "SPRO > Production > SFC > Order Types",
     "transaction_code": "OPJH", "status": "build", "priority": "high", "complexity": "medium",
     "estimated_hours": 6, "assigned_to": "Deniz Aydın"},
    {"code": "CFG-PP-002", "title": "MRP kontrol parametreleri (gıda tesis bazlı)",
     "module": "PP", "config_key": "SPRO > Production > MRP > Plant Parameters",
     "transaction_code": "OPPQ", "status": "design", "priority": "high", "complexity": "medium",
     "estimated_hours": 8, "assigned_to": "Deniz Aydın"},
    {"code": "CFG-QM-001", "title": "Muayene planı ve HACCP kontrol noktası",
     "module": "QM", "config_key": "SPRO > QM > Inspection Planning > Inspection Plan",
     "transaction_code": "QP01", "status": "design", "priority": "high", "complexity": "medium",
     "estimated_hours": 10, "assigned_to": "Deniz Aydın"},
    {"code": "CFG-EWM-001", "title": "Depo yapısı ve raf tipi tanımlama",
     "module": "EWM", "config_key": "SPRO > EWM > Master Data > Warehouse Structure",
     "transaction_code": "/SCWM/T340D", "status": "build", "priority": "high", "complexity": "medium",
     "estimated_hours": 12, "assigned_to": "Gökhan Demir"},
    {"code": "CFG-BASIS-001", "title": "Yetkilendirme rol tanımlama (Fiori + SOD)",
     "module": "Basis", "config_key": "PFCG Role Maintenance — Fiori Catalog/Group",
     "transaction_code": "PFCG", "status": "design", "priority": "critical", "complexity": "high",
     "estimated_hours": 40, "assigned_to": "Murat Çelik"},
]
