"""
Phase 5 — Sprints, Backlog Items (WRICEF), Config Items
Company: Anadolu Food & Beverage Inc.

3  Sprint (completed, completed, active)
28 Backlog Items (4W, 6R, 6I, 4C, 5E, 3F)
12 Config Items
"""

SPRINTS = [
    {
        "name": "Sprint 1 — Core Configuration",
        "goal": "FI/CO, MM, SD core configuration. Company code, plant, warehouse, chart of accounts definitions.",
        "status": "completed", "start_date": "2026-01-05", "end_date": "2026-01-16",
        "capacity_points": 45, "velocity": 42, "order": 1,
    },
    {
        "name": "Sprint 2 — WRICEF Development I",
        "goal": "First 10 WRICEF objects: e-Invoice, procurement WF, tax BAdI, migration templates.",
        "status": "completed", "start_date": "2026-01-19", "end_date": "2026-01-30",
        "capacity_points": 50, "velocity": 46, "order": 2,
    },
    {
        "name": "Sprint 3 — Integration & Test",
        "goal": "BTP interfaces, MES integration, SIT preparation, reporting development.",
        "status": "active", "start_date": "2026-02-02", "end_date": "2026-02-13",
        "capacity_points": 55, "velocity": None, "order": 3,
    },
]

BACKLOG_ITEMS = [
    # -- Workflows (W) -- 4 items -----------------------------------------------
    {"code": "WF-MM-001", "title": "Purchase order approval workflow (4-tier)",
     "wricef_type": "workflow", "module": "MM",
     "status": "closed", "priority": "critical", "story_points": 8, "estimated_hours": 40, "actual_hours": 36,
     "complexity": "high", "assigned_to": "Elif Kara", "sprint_idx": 0,
     "description": "Amount-based 4-tier approval: <TRY 25K automatic, <TRY 100K department manager, <TRY 500K director, >=TRY 500K CEO.",
     "transaction_code": "ME21N", "package": "ZMM_WF",
     "acceptance_criteria": "4 levels must be tested\nProxy approval must work"},
    {"code": "WF-FI-001", "title": "Invoice approval workflow (3-tier)",
     "wricef_type": "workflow", "module": "FI",
     "status": "deploy", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 20,
     "complexity": "medium", "assigned_to": "Ahmet Yildiz", "sprint_idx": 1,
     "description": "Incoming vendor invoice 3-tier approval. Amount and cost center based routing."},
    {"code": "WF-SD-001", "title": "Credit limit override approval workflow",
     "wricef_type": "workflow", "module": "SD",
     "status": "build", "priority": "medium", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Burak Sahin", "sprint_idx": 2},
    {"code": "WF-QM-001", "title": "Quality reject/accept approval workflow",
     "wricef_type": "workflow", "module": "QM",
     "status": "new", "priority": "medium", "story_points": 3, "estimated_hours": 16,
     "complexity": "low", "assigned_to": ""},

    # -- Reports (R) -- 6 items -------------------------------------------------
    {"code": "RPT-FI-001", "title": "Consolidated balance sheet report (TFRS/VUK)",
     "wricef_type": "report", "module": "FI",
     "status": "test", "priority": "critical", "story_points": 13, "estimated_hours": 64, "actual_hours": 58,
     "complexity": "very_high", "assigned_to": "Ahmet Yildiz", "sprint_idx": 1,
     "description": "Multi-company code consolidated balance sheet. TFRS and VUK parallel. Currency conversion."},
    {"code": "RPT-FI-002", "title": "Aging report (customer/vendor)",
     "wricef_type": "report", "module": "FI",
     "status": "closed", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 22,
     "complexity": "medium", "assigned_to": "Ahmet Yildiz", "sprint_idx": 0},
    {"code": "RPT-MM-001", "title": "Inventory turnover and shelf life analysis report",
     "wricef_type": "report", "module": "MM",
     "status": "build", "priority": "medium", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Elif Kara", "sprint_idx": 2},
    {"code": "RPT-SD-001", "title": "Sales performance dashboard (Fiori)",
     "wricef_type": "report", "module": "SD",
     "status": "design", "priority": "high", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": "Burak Sahin"},
    {"code": "RPT-PP-001", "title": "Production efficiency OEE report",
     "wricef_type": "report", "module": "PP",
     "status": "new", "priority": "medium", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": ""},
    {"code": "RPT-FI-003", "title": "VUK compliance statutory ledger report",
     "wricef_type": "report", "module": "FI",
     "status": "build", "priority": "critical", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": "Ahmet Yildiz", "sprint_idx": 2},

    # -- Interfaces (I) -- 6 items -----------------------------------------------
    {"code": "INT-SD-001", "title": "e-Invoice / e-Waybill GIB interface (UBL-TR)",
     "wricef_type": "interface", "module": "SD",
     "status": "test", "priority": "critical", "story_points": 13, "estimated_hours": 80, "actual_hours": 72,
     "complexity": "very_high", "assigned_to": "Zeynep Koc", "sprint_idx": 1,
     "description": "GIB e-Invoice/e-Waybill/e-Archive outbound/inbound. UBL-TR 1.2. BTP CPI iFlow.",
     "transaction_code": "VF01", "package": "ZSD_EINVOICE"},
    {"code": "INT-PP-001", "title": "MES -> SAP PP production confirmation interface",
     "wricef_type": "interface", "module": "PP",
     "status": "build", "priority": "high", "story_points": 8, "estimated_hours": 48,
     "complexity": "high", "assigned_to": "Zeynep Koc", "sprint_idx": 2,
     "description": "Production confirmations from MES, scrap reporting. OData + BTP CPI."},
    {"code": "INT-FI-001", "title": "Bank statement (MT940/camt.053) interface",
     "wricef_type": "interface", "module": "FI",
     "status": "design", "priority": "high", "story_points": 5, "estimated_hours": 32,
     "complexity": "medium", "assigned_to": "Zeynep Koc"},
    {"code": "INT-FI-002", "title": "Bank payment file submission (EFT/SWIFT)",
     "wricef_type": "interface", "module": "FI",
     "status": "new", "priority": "medium", "story_points": 5, "estimated_hours": 32,
     "complexity": "medium", "assigned_to": ""},
    {"code": "INT-SD-002", "title": "EDI order/shipment interface (EDIFACT)",
     "wricef_type": "interface", "module": "SD",
     "status": "new", "priority": "medium", "story_points": 8, "estimated_hours": 48,
     "complexity": "high", "assigned_to": ""},
    {"code": "INT-MM-001", "title": "WMS <-> EWM inventory synchronization interface",
     "wricef_type": "interface", "module": "MM",
     "status": "design", "priority": "high", "story_points": 8, "estimated_hours": 48,
     "complexity": "high", "assigned_to": "Gokhan Demir"},

    # -- Conversions (C) -- 4 items -----------------------------------------------
    {"code": "CNV-MD-001", "title": "Customer master data migration (15,000 records)",
     "wricef_type": "conversion", "module": "SD",
     "status": "test", "priority": "critical", "story_points": 8, "estimated_hours": 48, "actual_hours": 44,
     "complexity": "high", "assigned_to": "Hakan Gunes", "sprint_idx": 1,
     "description": "ECC KNA1/KNVV -> S/4 Business Partner migration. 15K active customers + address + contact."},
    {"code": "CNV-MD-002", "title": "Material master data migration (60,000 records — food/packaging)",
     "wricef_type": "conversion", "module": "MM",
     "status": "build", "priority": "critical", "story_points": 13, "estimated_hours": 64,
     "complexity": "very_high", "assigned_to": "Hakan Gunes", "sprint_idx": 2,
     "description": "MARA/MARC/MARD -> S/4 material migration. BOM, recipe, shelf life included."},
    {"code": "CNV-MD-003", "title": "Vendor master data migration (4,000 records)",
     "wricef_type": "conversion", "module": "MM",
     "status": "design", "priority": "high", "story_points": 5, "estimated_hours": 32,
     "complexity": "medium", "assigned_to": "Hakan Gunes"},
    {"code": "CNV-FI-001", "title": "Open item (AP/AR) and inventory balance migration",
     "wricef_type": "conversion", "module": "FI",
     "status": "new", "priority": "high", "story_points": 8, "estimated_hours": 40,
     "complexity": "high", "assigned_to": ""},

    # -- Enhancements (E) -- 5 items -----------------------------------------------
    {"code": "ENH-FI-001", "title": "Automatic tax calculation BAdI (VAT/SCT/PCST)",
     "wricef_type": "enhancement", "module": "FI",
     "status": "closed", "priority": "critical", "story_points": 5, "estimated_hours": 24, "actual_hours": 20,
     "complexity": "medium", "assigned_to": "Ahmet Yildiz", "sprint_idx": 0,
     "description": "VAT + SCT + PCST automatic calculation. Food product specific VAT 1%/10% differentiation.",
     "transaction_code": "FB01", "package": "ZFI_TAX"},
    {"code": "ENH-SD-001", "title": "Channel-based pricing condition type",
     "wricef_type": "enhancement", "module": "SD",
     "status": "deploy", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 22,
     "complexity": "medium", "assigned_to": "Burak Sahin", "sprint_idx": 1},
    {"code": "ENH-MM-001", "title": "Shelf life control — automatic FIFO/FEFO",
     "wricef_type": "enhancement", "module": "MM",
     "status": "build", "priority": "high", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Elif Kara", "sprint_idx": 2},
    {"code": "ENH-PP-001", "title": "Production order automatic release",
     "wricef_type": "enhancement", "module": "PP",
     "status": "new", "priority": "medium", "story_points": 3, "estimated_hours": 16,
     "complexity": "low", "assigned_to": ""},
    {"code": "ENH-QM-001", "title": "HACCP control point automatic inspection trigger",
     "wricef_type": "enhancement", "module": "QM",
     "status": "design", "priority": "high", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Deniz Aydin"},

    # -- Forms (F) -- 3 items -----------------------------------------------
    {"code": "FRM-SD-001", "title": "Delivery note (Adobe Form)",
     "wricef_type": "form", "module": "SD",
     "status": "closed", "priority": "high", "story_points": 5, "estimated_hours": 24, "actual_hours": 20,
     "complexity": "medium", "assigned_to": "Burak Sahin", "sprint_idx": 0,
     "description": "A4 delivery note. Company logo, barcode, signature field, lot/batch information."},
    {"code": "FRM-MM-001", "title": "Purchase order form (Adobe Form)",
     "wricef_type": "form", "module": "MM",
     "status": "test", "priority": "medium", "story_points": 3, "estimated_hours": 16, "actual_hours": 14,
     "complexity": "low", "assigned_to": "Elif Kara", "sprint_idx": 1},
    {"code": "FRM-QM-001", "title": "Quality certificate / analysis report form",
     "wricef_type": "form", "module": "QM",
     "status": "design", "priority": "medium", "story_points": 5, "estimated_hours": 24,
     "complexity": "medium", "assigned_to": "Deniz Aydin"},
]

CONFIG_ITEMS = [
    {"code": "CFG-FI-001", "title": "Company code definition (1000, 2000, 3000)",
     "module": "FI", "config_key": "SPRO > Enterprise Structure > FI > Define Company Code",
     "transaction_code": "OX02", "status": "closed", "priority": "critical", "complexity": "low",
     "estimated_hours": 4, "actual_hours": 3, "assigned_to": "Ahmet Yildiz"},
    {"code": "CFG-FI-002", "title": "Chart of accounts definition (CAGD — Food Turkey)",
     "module": "FI", "config_key": "SPRO > FI > GL > Define Chart of Accounts",
     "transaction_code": "OB13", "status": "closed", "priority": "critical", "complexity": "medium",
     "estimated_hours": 8, "actual_hours": 7, "assigned_to": "Ahmet Yildiz"},
    {"code": "CFG-FI-003", "title": "VAT tax codes (1% food, 10%, 20%, exempt)",
     "module": "FI", "config_key": "SPRO > FI > Tax > Define Tax Codes",
     "transaction_code": "FTXP", "status": "deploy", "priority": "critical", "complexity": "medium",
     "estimated_hours": 6, "actual_hours": 5, "assigned_to": "Ahmet Yildiz"},
    {"code": "CFG-MM-001", "title": "Purchasing organization and warehouse definition",
     "module": "MM", "config_key": "SPRO > Enterprise Structure > MM > Purchasing Org",
     "transaction_code": "OX08", "status": "closed", "priority": "high", "complexity": "low",
     "estimated_hours": 2, "actual_hours": 2, "assigned_to": "Elif Kara"},
    {"code": "CFG-MM-002", "title": "Material type (ZRAW, ZFRT, ZVER, ZAMB)",
     "module": "MM", "config_key": "SPRO > MM > Master Data > Material Types",
     "transaction_code": "OMS2", "status": "test", "priority": "high", "complexity": "medium",
     "estimated_hours": 8, "actual_hours": 7, "assigned_to": "Elif Kara"},
    {"code": "CFG-SD-001", "title": "Sales organization and distribution channel",
     "module": "SD", "config_key": "SPRO > Enterprise Structure > SD > Sales Org",
     "transaction_code": "OVX5", "status": "closed", "priority": "high", "complexity": "low",
     "estimated_hours": 4, "actual_hours": 3, "assigned_to": "Burak Sahin"},
    {"code": "CFG-SD-002", "title": "Pricing procedure (ZPRC01 — food)",
     "module": "SD", "config_key": "SPRO > SD > Pricing > Define Pricing Procedure",
     "transaction_code": "V/08", "status": "build", "priority": "critical", "complexity": "high",
     "estimated_hours": 16, "assigned_to": "Burak Sahin"},
    {"code": "CFG-PP-001", "title": "Production order type (ZPP1 process, ZPP2 discrete)",
     "module": "PP", "config_key": "SPRO > Production > SFC > Order Types",
     "transaction_code": "OPJH", "status": "build", "priority": "high", "complexity": "medium",
     "estimated_hours": 6, "assigned_to": "Deniz Aydin"},
    {"code": "CFG-PP-002", "title": "MRP control parameters (food plant-based)",
     "module": "PP", "config_key": "SPRO > Production > MRP > Plant Parameters",
     "transaction_code": "OPPQ", "status": "design", "priority": "high", "complexity": "medium",
     "estimated_hours": 8, "assigned_to": "Deniz Aydin"},
    {"code": "CFG-QM-001", "title": "Inspection plan and HACCP control point",
     "module": "QM", "config_key": "SPRO > QM > Inspection Planning > Inspection Plan",
     "transaction_code": "QP01", "status": "design", "priority": "high", "complexity": "medium",
     "estimated_hours": 10, "assigned_to": "Deniz Aydin"},
    {"code": "CFG-EWM-001", "title": "Warehouse structure and storage bin type definition",
     "module": "EWM", "config_key": "SPRO > EWM > Master Data > Warehouse Structure",
     "transaction_code": "/SCWM/T340D", "status": "build", "priority": "high", "complexity": "medium",
     "estimated_hours": 12, "assigned_to": "Gokhan Demir"},
    {"code": "CFG-BASIS-001", "title": "Authorization role definition (Fiori + SOD)",
     "module": "Basis", "config_key": "PFCG Role Maintenance — Fiori Catalog/Group",
     "transaction_code": "PFCG", "status": "design", "priority": "critical", "complexity": "high",
     "estimated_hours": 40, "assigned_to": "Murat Celik"},
]
