"""Integration Factory seed data — 2 waves, 8 interfaces."""

WAVES = [
    {
        "name": "Wave 1 — Core Interfaces",
        "status": "in_progress",
        "order": 1,
        "planned_start": "2026-03-01",
        "planned_end": "2026-04-30",
    },
    {
        "name": "Wave 2 — Extended Interfaces",
        "status": "planning",
        "order": 2,
        "planned_start": "2026-05-01",
        "planned_end": "2026-06-30",
    },
]

INTERFACES = [
    {
        "code": "IF-001",
        "name": "SAP → Bank Payment (SEPA XML)",
        "source_system": "S/4HANA",
        "target_system": "Garanti BBVA",
        "protocol": "file",
        "frequency": "daily",
        "direction": "outbound",
        "status": "integration_tested",
        "module": "FI",
        "wave_index": 0,
        "priority": "critical",
    },
    {
        "code": "IF-002",
        "name": "Bank Statement Import (MT940)",
        "source_system": "Garanti BBVA",
        "target_system": "S/4HANA",
        "protocol": "file",
        "frequency": "daily",
        "direction": "inbound",
        "status": "integration_tested",
        "module": "FI",
        "wave_index": 0,
        "priority": "critical",
    },
    {
        "code": "IF-003",
        "name": "e-Fatura GİB Entegrasyonu",
        "source_system": "S/4HANA",
        "target_system": "GİB Portal",
        "protocol": "soap",
        "frequency": "real-time",
        "direction": "bidirectional",
        "status": "developed",
        "module": "SD",
        "wave_index": 0,
        "priority": "critical",
    },
    {
        "code": "IF-004",
        "name": "MES Üretim Emirleri",
        "source_system": "S/4HANA",
        "target_system": "MES",
        "protocol": "bapi",
        "frequency": "real-time",
        "direction": "outbound",
        "status": "designed",
        "module": "PP",
        "wave_index": 0,
        "priority": "high",
    },
    {
        "code": "IF-005",
        "name": "WMS Depo Hareketleri",
        "source_system": "EWM",
        "target_system": "3PL WMS",
        "protocol": "idoc",
        "frequency": "hourly",
        "direction": "bidirectional",
        "status": "designed",
        "module": "EWM",
        "wave_index": 0,
        "priority": "high",
    },
    {
        "code": "IF-006",
        "name": "HR Master Data Sync",
        "source_system": "SuccessFactors",
        "target_system": "S/4HANA",
        "protocol": "odata",
        "frequency": "daily",
        "direction": "inbound",
        "status": "identified",
        "module": "HCM",
        "wave_index": 1,
        "priority": "medium",
    },
    {
        "code": "IF-007",
        "name": "CRM Müşteri Senkronizasyonu",
        "source_system": "Salesforce",
        "target_system": "S/4HANA",
        "protocol": "rest",
        "frequency": "real-time",
        "direction": "bidirectional",
        "status": "identified",
        "module": "SD",
        "wave_index": 1,
        "priority": "medium",
    },
    {
        "code": "IF-008",
        "name": "BI/BW Raporlama Extraction",
        "source_system": "S/4HANA",
        "target_system": "BW/4HANA",
        "protocol": "odata",
        "frequency": "daily",
        "direction": "outbound",
        "status": "identified",
        "module": "BC",
        "wave_index": 1,
        "priority": "medium",
    },
]
