"""
SEED-001 — L4 Seed Catalog: SAP Best Practice Reference Catalog
Project-independent global data for L4SeedCatalog model.

~90 entries covering SAP S/4HANA 2023 best-practice sub-processes:
  Order to Cash  (1OC, 2OC, 3OC)
  Procure to Pay (1MM, 2MM, 3MM)
  Finance        (1FI, 2FI, 3FI)
  Production     (1PP, 2PP)
  Warehouse      (1WM, 2WM)
  Quality        (1QM)
  Human Resources(1HR, 2HR)
"""

L4_CATALOG = [
    # ═════════════════════════════════════════════════════════════════════
    # ORDER TO CASH — 1OC: Sales Order Management
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1OC", "sub_process_code": "1OC-01",
     "sub_process_name": "Create Sales Order",
     "description": "Create standard sales order with item entry, partner determination and order confirmation.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1OC-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1OC", "sub_process_code": "1OC-02",
     "sub_process_name": "Pricing Determination",
     "description": "Automatic pricing via condition technique including discounts, surcharges and scales.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1OC-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1OC", "sub_process_code": "1OC-03",
     "sub_process_name": "Availability Check (ATP)",
     "description": "Check material availability against ATP quantities and confirmed delivery dates.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1OC-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1OC", "sub_process_code": "1OC-04",
     "sub_process_name": "Credit Check",
     "description": "Automatic credit limit check per customer using credit exposure and open items.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1OC-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1OC", "sub_process_code": "1OC-05",
     "sub_process_name": "Sales Order Confirmation & Output",
     "description": "Generate order confirmation output via BTP Forms and send to customer.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1OC-005", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1OC", "sub_process_code": "1OC-06",
     "sub_process_name": "Sales Order Change & Rejection",
     "description": "Modify or reject sales order items including reason code assignment.",
     "standard_sequence": 6, "bpmn_activity_id": "ACT-1OC-006", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1OC", "sub_process_code": "1OC-07",
     "sub_process_name": "Incomplete Order Processing",
     "description": "Handle incomplete orders via incompletion log and follow-up actions.",
     "standard_sequence": 7, "bpmn_activity_id": "ACT-1OC-007", "sap_release": "S/4HANA 2023"},

    # ── 2OC: Delivery & Shipping ─────────────────────────────────────────
    {"scope_item_code": "2OC", "sub_process_code": "2OC-01",
     "sub_process_name": "Create Outbound Delivery",
     "description": "Create outbound delivery from sales order with delivery scheduling and route determination.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-2OC-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2OC", "sub_process_code": "2OC-02",
     "sub_process_name": "Picking & Packing",
     "description": "Warehouse picking via wave management and packing with handling unit creation.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-2OC-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2OC", "sub_process_code": "2OC-03",
     "sub_process_name": "Post Goods Issue",
     "description": "Post goods issue for delivery triggering inventory reduction and revenue recognition.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-2OC-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2OC", "sub_process_code": "2OC-04",
     "sub_process_name": "Transportation Planning",
     "description": "Plan and execute transportation with carrier selection and freight cost calculation.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-2OC-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2OC", "sub_process_code": "2OC-05",
     "sub_process_name": "Proof of Delivery",
     "description": "Confirm delivery receipt with POD processing and difference handling.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-2OC-005", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2OC", "sub_process_code": "2OC-06",
     "sub_process_name": "Returns Processing",
     "description": "Process customer returns with return delivery, inspection and credit memo creation.",
     "standard_sequence": 6, "bpmn_activity_id": "ACT-2OC-006", "sap_release": "S/4HANA 2023"},

    # ── 3OC: Billing & Invoicing ─────────────────────────────────────────
    {"scope_item_code": "3OC", "sub_process_code": "3OC-01",
     "sub_process_name": "Create Billing Document",
     "description": "Create invoice from delivery or order with automatic billing due list processing.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-3OC-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3OC", "sub_process_code": "3OC-02",
     "sub_process_name": "Credit Memo & Debit Memo",
     "description": "Create credit/debit memos for price adjustments, returns and rebate settlements.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-3OC-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3OC", "sub_process_code": "3OC-03",
     "sub_process_name": "Revenue Recognition",
     "description": "Event-based revenue recognition per IFRS 15 with contract-based processing.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-3OC-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3OC", "sub_process_code": "3OC-04",
     "sub_process_name": "Invoice Output & e-Document",
     "description": "Generate invoice output in PDF/XML format including e-Invoice for tax authorities.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-3OC-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3OC", "sub_process_code": "3OC-05",
     "sub_process_name": "Rebate Agreement Processing",
     "description": "Manage volume-based rebate agreements with accrual posting and periodic settlement.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-3OC-005", "sap_release": "S/4HANA 2023"},

    # ═════════════════════════════════════════════════════════════════════
    # PROCURE TO PAY — 1MM: Procurement
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1MM", "sub_process_code": "1MM-01",
     "sub_process_name": "Create Purchase Requisition",
     "description": "Create purchase requisition manually or from MRP with approval workflow.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1MM-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1MM", "sub_process_code": "1MM-02",
     "sub_process_name": "Create Purchase Order",
     "description": "Create purchase order from requisition with vendor selection and conditions.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1MM-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1MM", "sub_process_code": "1MM-03",
     "sub_process_name": "Source Determination",
     "description": "Automatic source determination via source list, quota arrangement and contracts.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1MM-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1MM", "sub_process_code": "1MM-04",
     "sub_process_name": "Purchase Order Approval",
     "description": "Multi-level PO approval workflow based on value, material group and plant.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1MM-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1MM", "sub_process_code": "1MM-05",
     "sub_process_name": "Contract & Scheduling Agreement",
     "description": "Manage outline agreements, contracts and scheduling agreements with release orders.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1MM-005", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1MM", "sub_process_code": "1MM-06",
     "sub_process_name": "Vendor Evaluation",
     "description": "Automatic vendor evaluation based on delivery, quality, price and service criteria.",
     "standard_sequence": 6, "bpmn_activity_id": "ACT-1MM-006", "sap_release": "S/4HANA 2023"},

    # ── 2MM: Goods Receipt & Inventory ───────────────────────────────────
    {"scope_item_code": "2MM", "sub_process_code": "2MM-01",
     "sub_process_name": "Post Goods Receipt",
     "description": "Post goods receipt against PO with automatic account determination and GR/IR clearing.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-2MM-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2MM", "sub_process_code": "2MM-02",
     "sub_process_name": "Returns to Vendor",
     "description": "Process returns to vendor with return delivery and reversal of goods receipt.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-2MM-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2MM", "sub_process_code": "2MM-03",
     "sub_process_name": "Stock Transfer & Transfer Posting",
     "description": "Inter-plant and inter-storage location stock transfers with one-step or two-step processing.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-2MM-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2MM", "sub_process_code": "2MM-04",
     "sub_process_name": "Physical Inventory Count",
     "description": "Annual/periodic/cycle count inventory with count document, variance and adjustment posting.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-2MM-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2MM", "sub_process_code": "2MM-05",
     "sub_process_name": "Batch Management",
     "description": "Batch creation, classification and shelf-life management for traceable materials.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-2MM-005", "sap_release": "S/4HANA 2023"},

    # ── 3MM: Invoice Verification & Payment ──────────────────────────────
    {"scope_item_code": "3MM", "sub_process_code": "3MM-01",
     "sub_process_name": "Invoice Verification (3-Way Match)",
     "description": "Verify vendor invoices via 3-way match (PO / GR / Invoice) with tolerance check.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-3MM-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3MM", "sub_process_code": "3MM-02",
     "sub_process_name": "Evaluated Receipt Settlement (ERS)",
     "description": "Automatic invoice creation from goods receipt for ERS-flagged POs.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-3MM-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3MM", "sub_process_code": "3MM-03",
     "sub_process_name": "Blocked Invoice Processing",
     "description": "Handle blocked invoices from price variance, quantity difference or manual blocks.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-3MM-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3MM", "sub_process_code": "3MM-04",
     "sub_process_name": "Down Payment Processing",
     "description": "Manage vendor down payments: request, payment, clearing against final invoice.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-3MM-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3MM", "sub_process_code": "3MM-05",
     "sub_process_name": "GR/IR Clearing & Regrouping",
     "description": "Period-end GR/IR account analysis, clearing and balance regrouping.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-3MM-005", "sap_release": "S/4HANA 2023"},

    # ═════════════════════════════════════════════════════════════════════
    # FINANCE — 1FI: General Ledger & Closing
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1FI", "sub_process_code": "1FI-01",
     "sub_process_name": "Journal Entry Posting",
     "description": "Post manual and recurring journal entries with validation and substitution rules.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1FI-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1FI", "sub_process_code": "1FI-02",
     "sub_process_name": "Period-End Closing",
     "description": "Execute period-end closing activities: foreign currency valuation, reclassification, regrouping.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1FI-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1FI", "sub_process_code": "1FI-03",
     "sub_process_name": "Accruals & Deferrals",
     "description": "Automatic accrual/deferral posting with reversal scheduling.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1FI-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1FI", "sub_process_code": "1FI-04",
     "sub_process_name": "Financial Statements",
     "description": "Generate trial balance, balance sheet and P&L per financial statement version.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1FI-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1FI", "sub_process_code": "1FI-05",
     "sub_process_name": "Intercompany Reconciliation",
     "description": "Intercompany transaction matching, netting and elimination for group reporting.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1FI-005", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1FI", "sub_process_code": "1FI-06",
     "sub_process_name": "Tax Calculation & Reporting",
     "description": "Automatic tax code determination, VAT calculation and periodic tax returns.",
     "standard_sequence": 6, "bpmn_activity_id": "ACT-1FI-006", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1FI", "sub_process_code": "1FI-07",
     "sub_process_name": "Fixed Asset Accounting",
     "description": "Asset master management, acquisition, depreciation, transfer and retirement.",
     "standard_sequence": 7, "bpmn_activity_id": "ACT-1FI-007", "sap_release": "S/4HANA 2023"},

    # ── 2FI: Accounts Receivable ─────────────────────────────────────────
    {"scope_item_code": "2FI", "sub_process_code": "2FI-01",
     "sub_process_name": "Customer Invoice Processing",
     "description": "Post customer invoices with automatic payment term and dunning area determination.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-2FI-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2FI", "sub_process_code": "2FI-02",
     "sub_process_name": "Incoming Payment & Clearing",
     "description": "Post incoming payments with automatic open item clearing and bank reconciliation.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-2FI-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2FI", "sub_process_code": "2FI-03",
     "sub_process_name": "Dunning Process",
     "description": "Automatic dunning run with multi-level dunning notices and escalation procedures.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-2FI-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2FI", "sub_process_code": "2FI-04",
     "sub_process_name": "Customer Credit Management",
     "description": "Credit limit management, exposure calculation and release workflow for blocked orders.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-2FI-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2FI", "sub_process_code": "2FI-05",
     "sub_process_name": "Customer Down Payment",
     "description": "Customer down payment request, receipt, clearing and tax handling.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-2FI-005", "sap_release": "S/4HANA 2023"},

    # ── 3FI: Accounts Payable ────────────────────────────────────────────
    {"scope_item_code": "3FI", "sub_process_code": "3FI-01",
     "sub_process_name": "Vendor Invoice Processing",
     "description": "Post vendor invoices with tax code validation and payment baseline date calculation.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-3FI-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3FI", "sub_process_code": "3FI-02",
     "sub_process_name": "Outgoing Payment Run",
     "description": "Automatic payment run with bank transfer, check and payment medium generation.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-3FI-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3FI", "sub_process_code": "3FI-03",
     "sub_process_name": "Vendor Down Payment",
     "description": "Vendor down payment request, disbursement and clearing against final invoice.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-3FI-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3FI", "sub_process_code": "3FI-04",
     "sub_process_name": "Bank Reconciliation",
     "description": "Electronic bank statement import, automatic matching and manual clearing.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-3FI-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "3FI", "sub_process_code": "3FI-05",
     "sub_process_name": "Withholding Tax Processing",
     "description": "Calculate and post withholding tax at invoice or payment time per local regulations.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-3FI-005", "sap_release": "S/4HANA 2023"},

    # ═════════════════════════════════════════════════════════════════════
    # PRODUCTION — 1PP: Production Planning & MRP
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1PP", "sub_process_code": "1PP-01",
     "sub_process_name": "MRP Run & Evaluation",
     "description": "Execute MRP run with net requirements calculation, firming and exception message processing.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1PP-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1PP", "sub_process_code": "1PP-02",
     "sub_process_name": "Planned Order Conversion",
     "description": "Convert planned orders to production orders or purchase requisitions.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1PP-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1PP", "sub_process_code": "1PP-03",
     "sub_process_name": "Production Scheduling",
     "description": "Detailed scheduling with capacity leveling and sequencing via PP/DS or MRP Live.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1PP-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1PP", "sub_process_code": "1PP-04",
     "sub_process_name": "Demand Management & Forecasting",
     "description": "Create planned independent requirements from sales forecast and consumption-based planning.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1PP-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1PP", "sub_process_code": "1PP-05",
     "sub_process_name": "BOM & Routing Management",
     "description": "Create and maintain bills of material and routings with version management.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1PP-005", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1PP", "sub_process_code": "1PP-06",
     "sub_process_name": "Long-Term Planning Simulation",
     "description": "Simulate long-term production plans with what-if scenarios for capacity and material.",
     "standard_sequence": 6, "bpmn_activity_id": "ACT-1PP-006", "sap_release": "S/4HANA 2023"},

    # ── 2PP: Shop Floor Execution ────────────────────────────────────────
    {"scope_item_code": "2PP", "sub_process_code": "2PP-01",
     "sub_process_name": "Production Order Release",
     "description": "Release production order with availability check and capacity allocation.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-2PP-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2PP", "sub_process_code": "2PP-02",
     "sub_process_name": "Goods Issue to Production",
     "description": "Issue raw materials and components to production order from warehouse.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-2PP-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2PP", "sub_process_code": "2PP-03",
     "sub_process_name": "Operation Confirmation",
     "description": "Confirm production operations with actual quantities, times and scrap reporting.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-2PP-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2PP", "sub_process_code": "2PP-04",
     "sub_process_name": "Goods Receipt from Production",
     "description": "Post goods receipt of finished product to warehouse with automatic cost settlement.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-2PP-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2PP", "sub_process_code": "2PP-05",
     "sub_process_name": "Production Order Settlement",
     "description": "Settle production order costs to cost objects with variance analysis.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-2PP-005", "sap_release": "S/4HANA 2023"},

    # ═════════════════════════════════════════════════════════════════════
    # WAREHOUSE — 1WM: Inbound Warehouse
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1WM", "sub_process_code": "1WM-01",
     "sub_process_name": "Inbound Delivery Processing",
     "description": "Create inbound delivery from PO, plan unloading and quality inspection allocation.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1WM-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1WM", "sub_process_code": "1WM-02",
     "sub_process_name": "Putaway Strategy & Execution",
     "description": "Execute putaway with warehouse task creation per storage type and section strategy.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1WM-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1WM", "sub_process_code": "1WM-03",
     "sub_process_name": "Goods Receipt in Warehouse",
     "description": "Confirm goods receipt warehouse task and update bin stock quantities.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1WM-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1WM", "sub_process_code": "1WM-04",
     "sub_process_name": "Quality Inspection in Warehouse",
     "description": "Route materials to QI area, await inspection results and post to available stock.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1WM-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1WM", "sub_process_code": "1WM-05",
     "sub_process_name": "Cross-Docking",
     "description": "Direct routing of inbound materials to outbound staging without putaway.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1WM-005", "sap_release": "S/4HANA 2023"},

    # ── 2WM: Outbound & Stock Management ─────────────────────────────────
    {"scope_item_code": "2WM", "sub_process_code": "2WM-01",
     "sub_process_name": "Outbound Delivery Processing",
     "description": "Process outbound delivery with wave management and picking task creation.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-2WM-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2WM", "sub_process_code": "2WM-02",
     "sub_process_name": "Stock Transfer Between Warehouses",
     "description": "Execute stock transfer orders between warehouses or storage types.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-2WM-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2WM", "sub_process_code": "2WM-03",
     "sub_process_name": "Physical Inventory in Warehouse",
     "description": "Warehouse-level physical inventory with bin-level counting and reconciliation.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-2WM-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2WM", "sub_process_code": "2WM-04",
     "sub_process_name": "Replenishment",
     "description": "Automatic replenishment from reserve to fixed-bin picking areas per min/max levels.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-2WM-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2WM", "sub_process_code": "2WM-05",
     "sub_process_name": "Warehouse Reporting & Monitoring",
     "description": "Monitor warehouse KPIs: throughput, utilization, task backlog and SLA compliance.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-2WM-005", "sap_release": "S/4HANA 2023"},

    # ═════════════════════════════════════════════════════════════════════
    # QUALITY — 1QM: Quality Management
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1QM", "sub_process_code": "1QM-01",
     "sub_process_name": "Quality Planning",
     "description": "Define inspection plans, sampling procedures and dynamic modification rules.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1QM-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1QM", "sub_process_code": "1QM-02",
     "sub_process_name": "Inspection Lot Creation",
     "description": "Automatic inspection lot creation triggered by goods receipt, production or delivery.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1QM-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1QM", "sub_process_code": "1QM-03",
     "sub_process_name": "Results Recording & Usage Decision",
     "description": "Record inspection results, defects and make usage decision (accept/reject/rework).",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1QM-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1QM", "sub_process_code": "1QM-04",
     "sub_process_name": "Quality Notification",
     "description": "Create quality notifications for internal/external defects with root cause analysis.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1QM-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1QM", "sub_process_code": "1QM-05",
     "sub_process_name": "Certificate Management",
     "description": "Manage quality certificates for customers and from vendors per material specification.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1QM-005", "sap_release": "S/4HANA 2023"},

    # ═════════════════════════════════════════════════════════════════════
    # HUMAN RESOURCES — 1HR: Personnel Administration
    # ═════════════════════════════════════════════════════════════════════
    {"scope_item_code": "1HR", "sub_process_code": "1HR-01",
     "sub_process_name": "Hire Employee",
     "description": "Employee hiring with organizational assignment, infotype creation and contract generation.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-1HR-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1HR", "sub_process_code": "1HR-02",
     "sub_process_name": "Organizational Management",
     "description": "Maintain organizational units, positions and reporting relationships.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-1HR-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1HR", "sub_process_code": "1HR-03",
     "sub_process_name": "Personnel Change & Transfer",
     "description": "Process promotions, transfers, org reassignment and compensation changes.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-1HR-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1HR", "sub_process_code": "1HR-04",
     "sub_process_name": "Termination & Offboarding",
     "description": "Employee termination with severance calculation, asset return and access revocation.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-1HR-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "1HR", "sub_process_code": "1HR-05",
     "sub_process_name": "Payroll Processing",
     "description": "Run payroll with gross-to-net calculation, tax, social insurance and bank transfer.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-1HR-005", "sap_release": "S/4HANA 2023"},

    # ── 2HR: Time Management ─────────────────────────────────────────────
    {"scope_item_code": "2HR", "sub_process_code": "2HR-01",
     "sub_process_name": "Time Recording",
     "description": "Record working times via CATS, clock-in devices or employee self-service.",
     "standard_sequence": 1, "bpmn_activity_id": "ACT-2HR-001", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2HR", "sub_process_code": "2HR-02",
     "sub_process_name": "Absence Management",
     "description": "Manage leave requests, quotas, approval workflow and absence valuation.",
     "standard_sequence": 2, "bpmn_activity_id": "ACT-2HR-002", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2HR", "sub_process_code": "2HR-03",
     "sub_process_name": "Overtime & Shift Planning",
     "description": "Plan shifts, manage overtime approvals and calculate premium pay rates.",
     "standard_sequence": 3, "bpmn_activity_id": "ACT-2HR-003", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2HR", "sub_process_code": "2HR-04",
     "sub_process_name": "Time Evaluation",
     "description": "Execute time evaluation to calculate productive hours, overtime and time wage types.",
     "standard_sequence": 4, "bpmn_activity_id": "ACT-2HR-004", "sap_release": "S/4HANA 2023"},
    {"scope_item_code": "2HR", "sub_process_code": "2HR-05",
     "sub_process_name": "Attendance & Substitution",
     "description": "Track on-site attendance, business trips and substitution rules for approvers.",
     "standard_sequence": 5, "bpmn_activity_id": "ACT-2HR-005", "sap_release": "S/4HANA 2023"},
]
