"""
Aşama 2 — Scenarios (Signavio L1 Value Chain) + Workshops
Şirket: Anadolu Gıda ve İçecek A.Ş.

8 Scenario = 8 Signavio L1 Value Chain:
  - yonetimsel (2): Stratejik Planlama, Finans & Kontrol
  - cekirdek   (4): Sipariş→Nakit, Tedarik→Ödeme, Plan→Üret, Depo & Lojistik
  - destek     (2): İnsan Kaynakları, Bilgi Teknolojileri
"""

from datetime import datetime, timezone

SCENARIOS = [
    # ══════════════ YÖNETİMSEL ══════════════
    {
        "name": "Stratejik Planlama ve Bütçe Yönetimi",
        "description": "Yıllık bütçe planlama, tahmin, konsolidasyon ve yönetim raporlaması süreçleri.",
        "sap_module": "CO",
        "process_area": "record_to_report",
        "value_chain_category": "yonetimsel",
        "signavio_code": "L1.1",
        "status": "approved",
        "priority": "high",
        "owner": "Ahmet Yıldız",
        "workstream": "Finance (FI/CO)",
        "workshops": [
            {"title": "CO Maliyet Merkezi Planlama Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 5, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Ahmet Yıldız",
             "attendees": "CFO, Bütçe Müdürü, CO Danışmanı",
             "fit_count": 8, "gap_count": 2, "partial_fit_count": 1},
            {"title": "Yönetim Raporlama & SAC Demo",
             "session_type": "demo", "status": "completed",
             "session_date": datetime(2025, 10, 12, 10, 0, tzinfo=timezone.utc),
             "duration_minutes": 120, "facilitator": "Ahmet Yıldız",
             "attendees": "CFO, İç Denetim, Finans Ekibi"},
        ],
    },
    {
        "name": "Finansal Muhasebe ve Raporlama",
        "description": "Genel muhasebe, alacak/borç yönetimi, sabit kıymet, dönem kapanışı, vergi ve yasal raporlama.",
        "sap_module": "FI",
        "process_area": "record_to_report",
        "value_chain_category": "yonetimsel",
        "signavio_code": "L1.2",
        "status": "approved",
        "priority": "critical",
        "owner": "Ahmet Yıldız",
        "workstream": "Finance (FI/CO)",
        "workshops": [
            {"title": "FI Genel Muhasebe Fit-Gap Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 15, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Ahmet Yıldız",
             "attendees": "Muhasebe Müdürü, Mali İşler, YMM, FI Danışmanı",
             "fit_count": 15, "gap_count": 5, "partial_fit_count": 3},
            {"title": "Türk Vergi & e-Belge Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 22, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Ahmet Yıldız",
             "attendees": "YMM, Vergi Müdürü, GİB Entegrasyon Ekibi",
             "fit_count": 5, "gap_count": 4, "partial_fit_count": 2},
            {"title": "Sabit Kıymet & TFRS 16 Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 1, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Ahmet Yıldız",
             "attendees": "Muhasebe Müdürü, İç Denetim",
             "fit_count": 10, "gap_count": 1, "partial_fit_count": 2},
        ],
    },

    # ══════════════ ÇEKİRDEK ══════════════
    {
        "name": "Siparişten Nakite (Order-to-Cash)",
        "description": "Müşteri siparişi, fiyatlandırma, teslimat, faturalama, tahsilat uçtan uca süreci.",
        "sap_module": "SD",
        "process_area": "order_to_cash",
        "value_chain_category": "cekirdek",
        "signavio_code": "L1.3",
        "status": "approved",
        "priority": "critical",
        "owner": "Burak Şahin",
        "workstream": "Sales & Distribution (SD)",
        "workshops": [
            {"title": "SD Sipariş Yönetimi Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 18, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Burak Şahin",
             "attendees": "Satış Müdürü, Lojistik, Fiyatlandırma Ekibi",
             "fit_count": 12, "gap_count": 3, "partial_fit_count": 4},
            {"title": "Fiyatlandırma & İskonto Şemaları Workshop",
             "session_type": "design_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 8, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Burak Şahin",
             "attendees": "Ticari Direktör, Satış Planlama, Kategori Yöneticileri",
             "fit_count": 6, "gap_count": 4, "partial_fit_count": 2},
        ],
    },
    {
        "name": "Tedarikten Ödemeye (Procure-to-Pay)",
        "description": "Satınalma talebi, sipariş, mal girişi, fatura doğrulama, ödeme uçtan uca süreci.",
        "sap_module": "MM",
        "process_area": "procure_to_pay",
        "value_chain_category": "cekirdek",
        "signavio_code": "L1.4",
        "status": "approved",
        "priority": "critical",
        "owner": "Elif Kara",
        "workstream": "Materials Management (MM)",
        "workshops": [
            {"title": "MM Satınalma Süreçleri Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 20, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Elif Kara",
             "attendees": "Satınalma Müdürü, Depo Müdürü, Kalite Müdürü",
             "fit_count": 14, "gap_count": 2, "partial_fit_count": 3},
            {"title": "Stok Yönetimi & Değerleme Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 3, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Elif Kara",
             "attendees": "Stok Kontrol, Muhasebe, Lojistik",
             "fit_count": 8, "gap_count": 1, "partial_fit_count": 2},
        ],
    },
    {
        "name": "Plandan Üretime (Plan-to-Produce)",
        "description": "Talep planlama, MRP, üretim emri, üretim onayı, kalite kontrol uçtan uca süreci.",
        "sap_module": "PP",
        "process_area": "plan_to_produce",
        "value_chain_category": "cekirdek",
        "signavio_code": "L1.5",
        "status": "in_analysis",
        "priority": "critical",
        "owner": "Deniz Aydın",
        "workstream": "Production Planning (PP/QM)",
        "workshops": [
            {"title": "PP Üretim Planlama Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 15, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Deniz Aydın",
             "attendees": "Üretim Müdürü, Planlama Şefi, Kalite Müdürü, MES Sorumlusu",
             "fit_count": 10, "gap_count": 4, "partial_fit_count": 3},
            {"title": "QM Kalite & HACCP Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 22, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Deniz Aydın",
             "attendees": "Kalite Direktörü, HACCP Sorumlusu, Laboratuvar Şefi",
             "fit_count": 7, "gap_count": 3, "partial_fit_count": 2},
            {"title": "MES Entegrasyon Tasarım Workshop",
             "session_type": "design_workshop", "status": "completed",
             "session_date": datetime(2025, 11, 5, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Zeynep Koç",
             "attendees": "Üretim IT, MES Vendor, BTP Ekibi"},
        ],
    },
    {
        "name": "Depo ve Lojistik Yönetimi",
        "description": "Depo içi operasyonlar, raf yönetimi, sevkiyat, nakliye planlama.",
        "sap_module": "EWM",
        "process_area": "warehouse_mgmt",
        "value_chain_category": "cekirdek",
        "signavio_code": "L1.6",
        "status": "in_analysis",
        "priority": "high",
        "owner": "Gökhan Demir",
        "workstream": "Warehouse Management (EWM)",
        "workshops": [
            {"title": "EWM Depo Süreçleri Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 25, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Gökhan Demir",
             "attendees": "Depo Müdürü, Lojistik Müdürü, Sevkiyat Şefi",
             "fit_count": 9, "gap_count": 3, "partial_fit_count": 2},
        ],
    },

    # ══════════════ DESTEK ══════════════
    {
        "name": "İnsan Kaynakları Yönetimi",
        "description": "Personel yönetimi, bordro, izin, performans değerlendirme, eğitim takibi.",
        "sap_module": "HCM",
        "process_area": "hire_to_retire",
        "value_chain_category": "destek",
        "signavio_code": "L1.7",
        "status": "draft",
        "priority": "medium",
        "owner": "Seda Arslan",
        "workstream": "Human Capital (HCM)",
        "workshops": [
            {"title": "HCM Bordro & İzin Workshop",
             "session_type": "fit_gap_workshop", "status": "planned",
             "session_date": datetime(2025, 11, 20, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Seda Arslan",
             "attendees": "İK Müdürü, Bordro Uzmanı, İK Direktörü"},
        ],
    },
    {
        "name": "Bilgi Teknolojileri ve Altyapı",
        "description": "Yetkilendirme, Fiori, sistem yönetimi, monitoring, güvenlik.",
        "sap_module": "Basis",
        "process_area": "other",
        "value_chain_category": "destek",
        "signavio_code": "L1.8",
        "status": "in_analysis",
        "priority": "high",
        "owner": "Murat Çelik",
        "workstream": "Basis / Technology",
        "workshops": [
            {"title": "Yetkilendirme & SOD Workshop",
             "session_type": "design_workshop", "status": "completed",
             "session_date": datetime(2025, 11, 10, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Murat Çelik",
             "attendees": "IT Güvenlik, İç Denetim, Basis Ekibi",
             "fit_count": 5, "gap_count": 2, "partial_fit_count": 1},
            {"title": "Fiori Launchpad & UX Tasarım",
             "session_type": "demo", "status": "completed",
             "session_date": datetime(2025, 11, 15, 10, 0, tzinfo=timezone.utc),
             "duration_minutes": 180, "facilitator": "Murat Çelik",
             "attendees": "Key User'lar, UX Ekibi, İş Birimleri"},
        ],
    },
]
