"""
Phase 2 — Scenarios (Signavio L1 Value Chain) + Workshops
Company: Anadolu Food & Beverage Inc.

8 Scenario = 8 Signavio L1 Value Chain:
  - managerial (2): Strategic Planning, Finance & Control
  - core       (4): Order->Cash, Procure->Pay, Plan->Produce, Warehouse & Logistics
  - support    (2): Human Resources, Information Technology
"""

from datetime import datetime, timezone

SCENARIOS = [
    # ============== MANAGERIAL ==============
    {
        "name": "Strategic Planning and Budget Management",
        "description": "Annual budget planning, forecasting, consolidation and management reporting processes.",
        "sap_module": "CO",
        "process_area": "record_to_report",
        "value_chain_category": "managerial",
        "signavio_code": "L1.1",
        "status": "approved",
        "priority": "high",
        "owner": "Ahmet Yildiz",
        "workstream": "Finance (FI/CO)",
        "workshops": [
            {"title": "CO Cost Center Planning Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 5, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Ahmet Yildiz",
             "attendees": "CFO, Budget Manager, CO Consultant",
             "fit_count": 8, "gap_count": 2, "partial_fit_count": 1},
            {"title": "Management Reporting & SAC Demo",
             "session_type": "demo", "status": "completed",
             "session_date": datetime(2025, 10, 12, 10, 0, tzinfo=timezone.utc),
             "duration_minutes": 120, "facilitator": "Ahmet Yildiz",
             "attendees": "CFO, Internal Audit, Finance Team"},
        ],
    },
    {
        "name": "Financial Accounting and Reporting",
        "description": "General ledger, accounts receivable/payable, fixed assets, period close, tax and statutory reporting.",
        "sap_module": "FI",
        "process_area": "record_to_report",
        "value_chain_category": "managerial",
        "signavio_code": "L1.2",
        "status": "approved",
        "priority": "critical",
        "owner": "Ahmet Yildiz",
        "workstream": "Finance (FI/CO)",
        "workshops": [
            {"title": "FI General Ledger Fit-Gap Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 15, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Ahmet Yildiz",
             "attendees": "Accounting Manager, Financial Affairs, CPA, FI Consultant",
             "fit_count": 15, "gap_count": 5, "partial_fit_count": 3},
            {"title": "Turkish Tax & e-Document Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 22, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Ahmet Yildiz",
             "attendees": "CPA, Tax Manager, GIB Integration Team",
             "fit_count": 5, "gap_count": 4, "partial_fit_count": 2},
            {"title": "Fixed Asset & TFRS 16 Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 1, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Ahmet Yildiz",
             "attendees": "Accounting Manager, Internal Audit",
             "fit_count": 10, "gap_count": 1, "partial_fit_count": 2},
        ],
    },

    # ============== CORE ==============
    {
        "name": "Order to Cash (Order-to-Cash)",
        "description": "Customer order, pricing, delivery, billing, collection end-to-end process.",
        "sap_module": "SD",
        "process_area": "order_to_cash",
        "value_chain_category": "core",
        "signavio_code": "L1.3",
        "status": "approved",
        "priority": "critical",
        "owner": "Burak Sahin",
        "workstream": "Sales & Distribution (SD)",
        "workshops": [
            {"title": "SD Order Management Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 18, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Burak Sahin",
             "attendees": "Sales Manager, Logistics, Pricing Team",
             "fit_count": 12, "gap_count": 3, "partial_fit_count": 4},
            {"title": "Pricing & Discount Schemes Workshop",
             "session_type": "design_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 8, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Burak Sahin",
             "attendees": "Commercial Director, Sales Planning, Category Managers",
             "fit_count": 6, "gap_count": 4, "partial_fit_count": 2},
        ],
    },
    {
        "name": "Procure to Pay (Procure-to-Pay)",
        "description": "Purchase requisition, order, goods receipt, invoice verification, payment end-to-end process.",
        "sap_module": "MM",
        "process_area": "procure_to_pay",
        "value_chain_category": "core",
        "signavio_code": "L1.4",
        "status": "approved",
        "priority": "critical",
        "owner": "Elif Kara",
        "workstream": "Materials Management (MM)",
        "workshops": [
            {"title": "MM Procurement Processes Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 9, 20, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Elif Kara",
             "attendees": "Procurement Manager, Warehouse Manager, Quality Manager",
             "fit_count": 14, "gap_count": 2, "partial_fit_count": 3},
            {"title": "Inventory Management & Valuation Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 3, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Elif Kara",
             "attendees": "Inventory Control, Accounting, Logistics",
             "fit_count": 8, "gap_count": 1, "partial_fit_count": 2},
        ],
    },
    {
        "name": "Plan to Produce (Plan-to-Produce)",
        "description": "Demand planning, MRP, production order, production confirmation, quality control end-to-end process.",
        "sap_module": "PP",
        "process_area": "plan_to_produce",
        "value_chain_category": "core",
        "signavio_code": "L1.5",
        "status": "in_analysis",
        "priority": "critical",
        "owner": "Deniz Aydin",
        "workstream": "Production Planning (PP/QM)",
        "workshops": [
            {"title": "PP Production Planning Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 15, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Deniz Aydin",
             "attendees": "Production Manager, Planning Supervisor, Quality Manager, MES Officer",
             "fit_count": 10, "gap_count": 4, "partial_fit_count": 3},
            {"title": "QM Quality & HACCP Workshop",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 22, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Deniz Aydin",
             "attendees": "Quality Director, HACCP Officer, Lab Supervisor",
             "fit_count": 7, "gap_count": 3, "partial_fit_count": 2},
            {"title": "MES Integration Design Workshop",
             "session_type": "design_workshop", "status": "completed",
             "session_date": datetime(2025, 11, 5, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 240, "facilitator": "Zeynep Koc",
             "attendees": "Production IT, MES Vendor, BTP Team"},
        ],
    },
    {
        "name": "Warehouse and Logistics Management",
        "description": "Intra-warehouse operations, bin management, shipment, transportation planning.",
        "sap_module": "EWM",
        "process_area": "warehouse_mgmt",
        "value_chain_category": "core",
        "signavio_code": "L1.6",
        "status": "in_analysis",
        "priority": "high",
        "owner": "Gokhan Demir",
        "workstream": "Warehouse Management (EWM)",
        "workshops": [
            {"title": "EWM Warehouse Processes Fit-Gap",
             "session_type": "fit_gap_workshop", "status": "completed",
             "session_date": datetime(2025, 10, 25, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Gokhan Demir",
             "attendees": "Warehouse Manager, Logistics Manager, Dispatch Supervisor",
             "fit_count": 9, "gap_count": 3, "partial_fit_count": 2},
        ],
    },

    # ============== SUPPORT ==============
    {
        "name": "Human Resources Management",
        "description": "Personnel management, payroll, leave, performance evaluation, training tracking.",
        "sap_module": "HCM",
        "process_area": "hire_to_retire",
        "value_chain_category": "support",
        "signavio_code": "L1.7",
        "status": "draft",
        "priority": "medium",
        "owner": "Seda Arslan",
        "workstream": "Human Capital (HCM)",
        "workshops": [
            {"title": "HCM Payroll & Leave Workshop",
             "session_type": "fit_gap_workshop", "status": "planned",
             "session_date": datetime(2025, 11, 20, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 480, "facilitator": "Seda Arslan",
             "attendees": "HR Manager, Payroll Specialist, HR Director"},
        ],
    },
    {
        "name": "Information Technology and Infrastructure",
        "description": "Authorization, Fiori, system administration, monitoring, security.",
        "sap_module": "Basis",
        "process_area": "other",
        "value_chain_category": "support",
        "signavio_code": "L1.8",
        "status": "in_analysis",
        "priority": "high",
        "owner": "Murat Celik",
        "workstream": "Basis / Technology",
        "workshops": [
            {"title": "Authorization & SOD Workshop",
             "session_type": "design_workshop", "status": "completed",
             "session_date": datetime(2025, 11, 10, 9, 0, tzinfo=timezone.utc),
             "duration_minutes": 360, "facilitator": "Murat Celik",
             "attendees": "IT Security, Internal Audit, Basis Team",
             "fit_count": 5, "gap_count": 2, "partial_fit_count": 1},
            {"title": "Fiori Launchpad & UX Design",
             "session_type": "demo", "status": "completed",
             "session_date": datetime(2025, 11, 15, 10, 0, tzinfo=timezone.utc),
             "duration_minutes": 180, "facilitator": "Murat Celik",
             "attendees": "Key Users, UX Team, Business Units"},
        ],
    },
]
