"""Sprint 3: scenarios, requirements, requirement_traces

Revision ID: 3a4323d9a173
Revises: abaa5e4ab95f
Create Date: 2026-02-08 18:54:35.390970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4323d9a173'
down_revision = 'abaa5e4ab95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('req_parent_id', sa.Integer(), nullable=True, comment='Parent requirement for hierarchy'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Short requirement ID, e.g. REQ-FI-001'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('req_type', sa.String(length=50), nullable=True, comment='business | functional | technical | non_functional | integration'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='must_have | should_have | could_have | wont_have (MoSCoW)'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='draft | approved | in_progress | implemented | verified | deferred | rejected'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='Origin: business user, workshop, standard process, etc.'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='SAP module: FI, CO, MM, SD, PP, HCM, Basis, etc.'),
    sa.Column('fit_gap', sa.String(length=20), nullable=True, comment='fit | gap | partial_fit'),
    sa.Column('effort_estimate', sa.String(length=20), nullable=True, comment='xs | s | m | l | xl or story points'),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['req_parent_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(length=50), nullable=True, comment='approach | timeline | scope | cost | resource'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='draft | under_review | approved | rejected | archived'),
    sa.Column('is_baseline', sa.Boolean(), nullable=True, comment='Mark one scenario as the baseline / recommended option'),
    sa.Column('estimated_duration_weeks', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_resources', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='low | medium | high | critical'),
    sa.Column('confidence_pct', sa.Integer(), nullable=True, comment='Confidence level 0-100 for the estimate'),
    sa.Column('pros', sa.Text(), nullable=True, comment='Advantages — newline separated'),
    sa.Column('cons', sa.Text(), nullable=True, comment='Disadvantages — newline separated'),
    sa.Column('assumptions', sa.Text(), nullable=True, comment='Key assumptions — newline separated'),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='phase | workstream | scenario | requirement | gate'),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('trace_type', sa.String(length=50), nullable=True, comment='implements | depends_on | derived_from | tested_by | related_to'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='Parameter name'),
    sa.Column('value', sa.Text(), nullable=True, comment='Parameter value'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='general | technical | financial | organizational | timeline'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_parameters')
    op.drop_table('requirement_traces')
    op.drop_table('scenarios')
    op.drop_table('requirements')
    # ### end Alembic commands ###
