"""s5_04_fdd_i01_transport_cts

Revision ID: 44c13875cf94
Revises: 4b46186297a0
Create Date: 2026-02-22 22:39:22.784081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c13875cf94'
down_revision = '4b46186297a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_waves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_system', sa.String(length=5), nullable=False, comment='QAS | PRE | PRD'),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='planned | in_progress | completed | cancelled'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('planned','in_progress','completed','cancelled')", name='ck_transport_wave_status'),
    sa.ForeignKeyConstraint(['project_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_waves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_waves_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_waves_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_twav_tenant_project', ['tenant_id', 'project_id'], unique=False)

    op.create_table('transport_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transport_number', sa.String(length=20), nullable=False, comment='SAP CTS format: ^[A-Z]{3}K\\d{6}$ e.g. DEVK900123'),
    sa.Column('transport_type', sa.String(length=30), nullable=False, comment='workbench | customizing | support_pkg | transport_of_copies'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('sap_module', sa.String(length=10), nullable=True, comment='e.g. FI, MM, SD'),
    sa.Column('wave_id', sa.Integer(), nullable=True),
    sa.Column('current_system', sa.String(length=5), nullable=False, comment='DEV | QAS | PRE | PRD'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='created | released | imported | failed | locked'),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_log', sa.JSON(), nullable=True, comment='[{system, status, imported_at, return_code}] — appended per import event'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('created','released','imported','failed','locked')", name='ck_transport_req_status'),
    sa.CheckConstraint("transport_type IN ('workbench','customizing','support_pkg','transport_of_copies')", name='ck_transport_req_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wave_id'], ['transport_waves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_requests_transport_number'), ['transport_number'], unique=False)
        batch_op.create_index('ix_treq_tenant_project', ['tenant_id', 'project_id'], unique=False)

    op.create_table('transport_backlog_links',
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('backlog_item_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['backlog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_id'], ['transport_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transport_id', 'backlog_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_backlog_links')
    with op.batch_alter_table('transport_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_treq_tenant_project')
        batch_op.drop_index(batch_op.f('ix_transport_requests_transport_number'))
        batch_op.drop_index(batch_op.f('ix_transport_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_transport_requests_project_id'))

    op.drop_table('transport_requests')
    with op.batch_alter_table('transport_waves', schema=None) as batch_op:
        batch_op.drop_index('ix_twav_tenant_project')
        batch_op.drop_index(batch_op.f('ix_transport_waves_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_transport_waves_project_id'))

    op.drop_table('transport_waves')
    # ### end Alembic commands ###
