"""s5_03_fdd_i03_cutover_war_room

Revision ID: 4b46186297a0
Revises: 9033b00a7471
Create Date: 2026-02-22 22:28:11.045093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b46186297a0'
down_revision = '9033b00a7471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runbook_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workstream', sa.String(length=50), nullable=True, comment='technical | basis | functional | data | interface | communication'))
        batch_op.add_column(sa.Column('delay_minutes', sa.Integer(), nullable=True, comment='Auto-calculated: actual_end - planned_end in minutes. Negative = early.'))
        batch_op.add_column(sa.Column('is_critical_path', sa.Boolean(), nullable=False, comment='Set by calculate_critical_path() in cutover_service.'))
        batch_op.add_column(sa.Column('parallel_group', sa.String(length=20), nullable=True, comment='A | B | C — parallel execution lanes within a workstream.'))
        batch_op.add_column(sa.Column('issue_note', sa.Text(), nullable=True, comment='War-room issue flag. Set via flag_issue() endpoint.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runbook_tasks', schema=None) as batch_op:
        batch_op.drop_column('issue_note')
        batch_op.drop_column('parallel_group')
        batch_op.drop_column('is_critical_path')
        batch_op.drop_column('delay_minutes')
        batch_op.drop_column('workstream')

    # ### end Alembic commands ###
