"""sprint_6_raid_notifications

Revision ID: 6779a7d1c048
Revises: a7ac281a764b
Create Date: 2026-02-08 21:33:24.297713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6779a7d1c048'
down_revision = 'a7ac281a764b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=150), nullable=True, comment="User name or 'all' for broadcast"),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True, comment='risk/action/issue/decision/...'),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='Auto-generated: ACT-001'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=30), nullable=True, comment='risk/issue/requirement/...'),
    sa.Column('linked_entity_id', sa.Integer(), nullable=True),
    sa.Column('workstream_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='Auto-generated: DEC-001'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('decision_owner', sa.String(length=150), nullable=True, comment='Final approver / decision maker'),
    sa.Column('alternatives', sa.Text(), nullable=True, comment='JSON or freetext list of alternatives'),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('workstream_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='Auto-generated: ISS-001'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('escalation_path', sa.String(length=300), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('workstream_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='Auto-generated: RSK-001'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True, comment='1-5 scale'),
    sa.Column('impact', sa.Integer(), nullable=True, comment='1-5 scale'),
    sa.Column('risk_score', sa.Integer(), nullable=True, comment='probability × impact'),
    sa.Column('rag_status', sa.String(length=10), nullable=True, comment='green/amber/orange/red'),
    sa.Column('risk_category', sa.String(length=30), nullable=True),
    sa.Column('risk_response', sa.String(length=20), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('contingency_plan', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.String(length=300), nullable=True),
    sa.Column('workstream_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risks')
    op.drop_table('issues')
    op.drop_table('decisions')
    op.drop_table('actions')
    op.drop_table('notifications')
    # ### end Alembic commands ###
