"""Sprint 5 — Test Hub: test_plans, test_cycles, test_cases, test_executions, defects

Revision ID: 6c38e0d8be70
Revises: a1cedac8e083
Create Date: 2026-02-08 20:30:34.299380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c38e0d8be70'
down_revision = 'a1cedac8e083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='e.g. SIT Master Plan, UAT Plan v2'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True, comment='draft | active | completed | cancelled'),
    sa.Column('test_strategy', sa.Text(), nullable=True, comment='High-level test approach / strategy notes'),
    sa.Column('entry_criteria', sa.Text(), nullable=True, comment='Conditions to start this plan'),
    sa.Column('exit_criteria', sa.Text(), nullable=True, comment='Conditions to close this plan'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='e.g. SIT Cycle 1'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True, comment='planning | in_progress | completed | cancelled'),
    sa.Column('test_layer', sa.String(length=30), nullable=True, comment='unit | sit | uat | regression | performance | cutover_rehearsal'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True, comment='Sort order within plan'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True, comment='Linked requirement for traceability'),
    sa.Column('backlog_item_id', sa.Integer(), nullable=True, comment='Linked WRICEF backlog item'),
    sa.Column('config_item_id', sa.Integer(), nullable=True, comment='Linked config item'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Auto or manual code, e.g. TC-FI-001, TC-SD-042'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_layer', sa.String(length=30), nullable=True, comment='unit | sit | uat | regression | performance | cutover_rehearsal'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='SAP module: FI, MM, SD, etc.'),
    sa.Column('preconditions', sa.Text(), nullable=True, comment='Setup / preconditions'),
    sa.Column('test_steps', sa.Text(), nullable=True, comment='Step-by-step test procedure'),
    sa.Column('expected_result', sa.Text(), nullable=True, comment='Expected outcome'),
    sa.Column('test_data_set', sa.Text(), nullable=True, comment='Test data description or reference'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='draft | ready | approved | deprecated'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='low | medium | high | critical'),
    sa.Column('is_regression', sa.Boolean(), nullable=True, comment='Flagged for regression set (re-run on upgrades/releases)'),
    sa.Column('assigned_to', sa.String(length=100), nullable=True, comment='Tester name'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['backlog_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['config_item_id'], ['config_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True, comment='Test case that found this defect'),
    sa.Column('backlog_item_id', sa.Integer(), nullable=True, comment='Linked WRICEF item (fix target)'),
    sa.Column('config_item_id', sa.Integer(), nullable=True, comment='Linked config item (fix target)'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Auto code, e.g. DEF-0001, DEF-FI-042'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True, comment='P1 (blocker) | P2 (critical) | P3 (major) | P4 (minor/cosmetic)'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='new | open | in_progress | fixed | retest | closed | rejected | reopened'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='SAP module'),
    sa.Column('environment', sa.String(length=50), nullable=True, comment='DEV | QAS | PRD'),
    sa.Column('reported_by', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('found_in_cycle', sa.String(length=100), nullable=True, comment='Which test cycle found it'),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=True, comment='Number of times reopened'),
    sa.Column('resolution', sa.Text(), nullable=True, comment='Fix description'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='Root cause analysis'),
    sa.Column('transport_request', sa.String(length=30), nullable=True, comment='SAP transport for the fix'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['backlog_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['config_item_id'], ['config_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True, comment='not_run | pass | fail | blocked | deferred'),
    sa.Column('executed_by', sa.String(length=100), nullable=True, comment='Tester name'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Execution time in minutes'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Execution notes / evidence'),
    sa.Column('evidence_url', sa.String(length=500), nullable=True, comment='Screenshot / log URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['test_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_executions')
    op.drop_table('defects')
    op.drop_table('test_cases')
    op.drop_table('test_cycles')
    op.drop_table('test_plans')
    # ### end Alembic commands ###
