"""add project_charters system_landscapes scope_assessments S3-01

Revision ID: 9a4f96a6db5a
Revises: f0g1h2i3j429
Create Date: 2026-02-22 20:24:14.748168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4f96a6db5a'
down_revision = 'f0g1h2i3j429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_type', sa.String(length=32), nullable=True, comment='business | functional | technical | non_functional | integration'))
        batch_op.add_column(sa.Column('moscow_priority', sa.String(length=20), nullable=True, comment='must_have | should_have | could_have | wont_have (MoSCoW)'))
        batch_op.add_column(sa.Column('source', sa.String(length=32), nullable=True, comment='workshop | stakeholder | regulation | gap_analysis | standard_process'))
        batch_op.add_column(sa.Column('parent_id', sa.String(length=36), nullable=True, comment='Epic → Feature → User Story hierarchy; self-referential'))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True, comment='SAP Cloud ALM / Jira / ServiceNow external ID'))
        batch_op.add_column(sa.Column('legacy_requirement_id', sa.Integer(), nullable=True, comment='requirements.id of the migrated legacy row — for backward trace'))
        batch_op.create_index(batch_op.f('ix_explore_requirements_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_explore_requirements_legacy_requirement_id'), ['legacy_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_explore_requirements_parent_id'), ['parent_id'], unique=False)
        # Note: FK from parent_id → explore_requirements.id is intentionally
        # omitted here; SQLite batch mode does not support adding a FK whose
        # referencing column (String 36) differs in type from the PK (Integer).
        # The self-referential hierarchy is maintained at the application layer.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explore_requirements_parent_id'))
        batch_op.drop_index(batch_op.f('ix_explore_requirements_legacy_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_explore_requirements_external_id'))
        batch_op.drop_column('legacy_requirement_id')
        batch_op.drop_column('external_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('source')
        batch_op.drop_column('moscow_priority')
        batch_op.drop_column('requirement_type')

    # ### end Alembic commands ###
