"""Sprint 4 gap fix - config_items functional_specs technical_specs

Revision ID: a1cedac8e083
Revises: c4b1e8f23a01
Create Date: 2026-02-08 19:42:36.911831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cedac8e083'
down_revision = 'c4b1e8f23a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True, comment='Link to source requirement'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Short ID, e.g. CFG-FI-001, CFG-SD-042'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True, comment='SAP module: FI, CO, MM, SD, PP, etc.'),
    sa.Column('config_key', sa.String(length=100), nullable=True, comment='IMG path or config key, e.g. SPRO > FI > Tax > Define Tax Codes'),
    sa.Column('transaction_code', sa.String(length=30), nullable=True, comment='Customizing T-code: OB40, OVZG, etc.'),
    sa.Column('transport_request', sa.String(length=30), nullable=True, comment='SAP transport request number for config transport'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='new | design | build | test | deploy | closed | blocked | cancelled'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='low | medium | high | critical'),
    sa.Column('assigned_to', sa.String(length=100), nullable=True, comment='Functional consultant name'),
    sa.Column('complexity', sa.String(length=20), nullable=True, comment='low | medium | high'),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backlog_item_id', sa.Integer(), nullable=True, comment='Link to WRICEF item (mutually exclusive with config_item_id)'),
    sa.Column('config_item_id', sa.Integer(), nullable=True, comment='Link to config item (mutually exclusive with backlog_item_id)'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True, comment='Full FS document body (Markdown/HTML)'),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True, comment='draft | in_review | approved | rework'),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backlog_item_id'], ['backlog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_item_id'], ['config_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('functional_spec_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True, comment='Full TS document body (Markdown/HTML)'),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True, comment='draft | in_review | approved | rework'),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objects_list', sa.Text(), nullable=True, comment='List of technical objects (classes, function modules, tables, etc.)'),
    sa.Column('unit_test_evidence', sa.Text(), nullable=True, comment='Unit test results / evidence reference'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['functional_spec_id'], ['functional_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_specs')
    op.drop_table('functional_specs')
    op.drop_table('config_items')
    # ### end Alembic commands ###
