"""sprint_3_scope_process_analysis_models

Revision ID: a7ac281a764b
Revises: 6c38e0d8be70
Create Date: 2026-02-08 21:07:25.493762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ac281a764b'
down_revision = '6c38e0d8be70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent process for hierarchy'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=5), nullable=True, comment='L1 | L2 | L3'),
    sa.Column('process_id_code', sa.String(length=50), nullable=True, comment='SAP process ID, e.g. O2C, P2P, RTR'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='SAP module: FI, CO, MM, SD, PP, etc.'),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='SAP scope item code, e.g. 1NS, 2OC, BD9'),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sap_reference', sa.String(length=100), nullable=True, comment='SAP Best Practice reference ID'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='active | deferred | out_of_scope | in_scope'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='low | medium | high | critical'),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.String(length=30), nullable=True, comment='workshop | fit_gap | demo | prototype | review'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='planned | in_progress | completed | cancelled'),
    sa.Column('fit_gap_result', sa.String(length=20), nullable=True, comment='fit | partial_fit | gap'),
    sa.Column('decision', sa.Text(), nullable=True, comment='Workshop outcome / decision'),
    sa.Column('attendees', sa.Text(), nullable=True, comment='Comma-separated names'),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('scope_items')
    op.drop_table('processes')
    # ### end Alembic commands ###
