"""Sprint 1+2: programs, phases, gates, workstreams, team_members, committees

Revision ID: abaa5e4ab95f
Revises: 
Create Date: 2026-02-08 18:38:14.462121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaa5e4ab95f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True, comment='greenfield | brownfield | bluefield | selective_data_transition'),
    sa.Column('methodology', sa.String(length=50), nullable=True, comment='sap_activate | agile | waterfall | hybrid'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='planning | active | on_hold | completed | cancelled'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='low | medium | high | critical'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('go_live_date', sa.Date(), nullable=True),
    sa.Column('sap_product', sa.String(length=50), nullable=True, comment='S/4HANA | SuccessFactors | Ariba | BTP | Other'),
    sa.Column('deployment_option', sa.String(length=30), nullable=True, comment='on_premise | cloud | hybrid'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('committee_type', sa.String(length=50), nullable=True, comment='steering | advisory | review | working_group'),
    sa.Column('meeting_frequency', sa.String(length=30), nullable=True, comment='daily | weekly | biweekly | monthly | ad_hoc'),
    sa.Column('chair_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True, comment='Sort order within program'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='not_started | in_progress | completed | skipped'),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('completion_pct', sa.Integer(), nullable=True, comment='0-100'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workstreams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ws_type', sa.String(length=30), nullable=True, comment='functional | technical | cross_cutting'),
    sa.Column('lead_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True, comment='active | on_hold | completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gate_type', sa.String(length=30), nullable=True, comment='quality_gate | milestone | decision_point'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='pending | passed | failed | waived'),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True, comment='Acceptance criteria / checklist'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True, comment='program_manager | project_lead | stream_lead | consultant | developer | team_member'),
    sa.Column('raci', sa.String(length=20), nullable=True, comment='responsible | accountable | consulted | informed'),
    sa.Column('workstream_id', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True, comment='Company / partner name'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('gates')
    op.drop_table('workstreams')
    op.drop_table('phases')
    op.drop_table('committees')
    op.drop_table('programs')
    # ### end Alembic commands ###
