"""change_management_tables

Revision ID: b3edac26afaa
Revises: a7502090be66
Create Date: 2026-03-12 21:07:56.448445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b3edac26afaa'
down_revision = 'a7502090be66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_actions_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_approval_workflows_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_att_project'))
        batch_op.create_index('idx_att_program', ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_program_id'), ['program_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('backlog_items', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_backlog_items_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_committees_project_id_projects'), type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_config_items_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cutover_plans', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_cutover_plans_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_decisions_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_defects_linked_requirement_id'), ['linked_requirement_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_defects_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'requirements', ['linked_requirement_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('execution_id')

    with op.batch_alter_table('explore_decisions', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_explore_decisions_program_id'), ['program_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('explore_open_items', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_eoi_project_status'))
        batch_op.drop_constraint(batch_op.f('uq_eoi_project_code'), type_='unique')
        batch_op.create_index('idx_eoi_program_status', ['program_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_explore_open_items_program_id'), ['program_id'], unique=False)
        batch_op.create_unique_constraint('uq_eoi_program_code', ['program_id', 'code'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('explore_requirements', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_ereq_project_area'))
        batch_op.drop_index(batch_op.f('idx_ereq_project_priority'))
        batch_op.drop_index(batch_op.f('idx_ereq_project_status'))
        batch_op.drop_index(batch_op.f('ix_ereq_delivery_pattern'))
        batch_op.drop_index(batch_op.f('ix_ereq_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_ereq_requirement_class'))
        batch_op.drop_index(batch_op.f('ix_ereq_trigger_reason'))
        batch_op.drop_constraint(batch_op.f('uq_ereq_project_code'), type_='unique')
        batch_op.create_index('idx_ereq_program_area', ['program_id', 'process_area'], unique=False)
        batch_op.create_index('idx_ereq_program_priority', ['program_id', 'priority'], unique=False)
        batch_op.create_index('idx_ereq_program_status', ['program_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_explore_requirements_program_id'), ['program_id'], unique=False)
        batch_op.create_unique_constraint('uq_ereq_program_code', ['program_id', 'code'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('delivery_pattern')
        batch_op.drop_column('trigger_reason')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('requirement_class')

    with op.batch_alter_table('explore_workshops', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_ews_project_area'))
        batch_op.drop_index(batch_op.f('idx_ews_project_date'))
        batch_op.drop_index(batch_op.f('idx_ews_project_status'))
        batch_op.drop_constraint(batch_op.f('uq_ews_project_code'), type_='unique')
        batch_op.create_index('idx_ews_program_area', ['program_id', 'process_area'], unique=False)
        batch_op.create_index('idx_ews_program_date', ['program_id', 'date'], unique=False)
        batch_op.create_index('idx_ews_program_status', ['program_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_explore_workshops_program_id'), ['program_id'], unique=False)
        batch_op.create_unique_constraint('uq_ews_program_code', ['program_id', 'code'])
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hypercare_incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'hypercare_war_rooms', ['war_room_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interfaces_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_interfaces_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_issues_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('open_item_comments', schema=None) as batch_op:
        batch_op.create_index('ix_oic_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_item_comments_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_item_comments_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('phase_gates', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_phase_gates_program_id'), ['program_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_phases_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('post_golive_change_requests', schema=None) as batch_op:
        batch_op.create_index('ix_pgcr_tenant_project', ['tenant_id', 'project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_golive_change_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'hypercare_war_rooms', ['war_room_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('process_levels', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_pl_project_level'))
        batch_op.drop_index(batch_op.f('idx_pl_project_parent'))
        batch_op.drop_index(batch_op.f('idx_pl_project_scope_item'))
        batch_op.drop_index(batch_op.f('idx_pl_scope_item'))
        batch_op.drop_constraint(batch_op.f('uq_pl_project_code'), type_='unique')
        batch_op.create_index('idx_pl_program_level', ['program_id', 'level'], unique=False)
        batch_op.create_index('idx_pl_program_parent', ['program_id', 'parent_id'], unique=False)
        batch_op.create_index('idx_pl_program_scope_item', ['program_id', 'scope_item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_levels_program_id'), ['program_id'], unique=False)
        batch_op.create_unique_constraint('uq_pl_program_code', ['program_id', 'code'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_process_steps_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_steps_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_ps_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('process_variant_imports', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('idx_pvi_tenant_program', ['tenant_id', 'program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_variant_imports_program_id'), ['program_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_roles', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_prole_project_user_role_area'), type_='unique')
        batch_op.create_index(batch_op.f('ix_project_roles_program_id'), ['program_id'], unique=False)
        batch_op.create_unique_constraint('uq_prole_program_user_role_area', ['program_id', 'user_id', 'role', 'process_area'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raci_activities', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('ix_raci_activity_tenant_project', ['tenant_id', 'project_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_raci_activities_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('raci_entries', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index('ix_raci_entry_project_activity', ['project_id', 'activity_id'], unique=False)
        batch_op.create_index('ix_raci_entry_tenant_project', ['tenant_id', 'project_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_raci_entries_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('requirement_dependencies', schema=None) as batch_op:
        batch_op.create_index('ix_rdep_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_dependencies_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_dependencies_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('requirement_open_item_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_open_item_links_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_open_item_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_roil_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_requirements_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_risks_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scope_change_logs', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_scl_project'))
        batch_op.create_index('idx_scl_program', ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_change_logs_program_id'), ['program_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scope_change_requests', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_scr_project_status'))
        batch_op.drop_constraint(batch_op.f('uq_scr_project_code'), type_='unique')
        batch_op.create_index('idx_scr_program_status', ['program_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_change_requests_program_id'), ['program_id'], unique=False)
        batch_op.create_unique_constraint('uq_scr_program_code', ['program_id', 'code'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_sprints_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_team_members_project_id_projects'), type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_test_cases_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_suite_id'), ['suite_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_test_cases_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'test_suites', ['suite_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test_cycles', schema=None) as batch_op:
        batch_op.drop_column('owner_id')
        batch_op.drop_column('release_train')
        batch_op.drop_column('deployment_batch')
        batch_op.drop_column('transport_request')

    with op.batch_alter_table('test_daily_snapshots', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_test_daily_snapshots_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_test_plans_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_test_suites_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_role'), type_='unique')
        batch_op.create_index('ix_user_roles_scope_lookup', ['user_id', 'tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_role_scoped', ['user_id', 'role_id', 'tenant_id', 'program_id', 'project_id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('waves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waves_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_waves_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('workshop_agenda_items', schema=None) as batch_op:
        batch_op.create_index('ix_wai_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_agenda_items_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_agenda_items_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workshop_attendees', schema=None) as batch_op:
        batch_op.create_index('ix_wa_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_attendees_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_attendees_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workshop_scope_items', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_workshop_scope_items_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_scope_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_wsi_tenant_program_project', ['tenant_id', 'program_id', 'project_id'], unique=False)
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workstreams', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_workstreams_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstreams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workstreams_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('workshop_scope_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_wsi_tenant_program_project')
        batch_op.drop_index(batch_op.f('ix_workshop_scope_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_scope_items_program_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('workshop_attendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workshop_attendees_project_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_attendees_program_id'))
        batch_op.drop_index('ix_wa_tenant_program_project')

    with op.batch_alter_table('workshop_agenda_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workshop_agenda_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_agenda_items_program_id'))
        batch_op.drop_index('ix_wai_tenant_program_project')

    with op.batch_alter_table('waves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_waves_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('ix_waves_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_role_scoped', type_='unique')
        batch_op.drop_index('ix_user_roles_scope_lookup')
        batch_op.create_unique_constraint(batch_op.f('uq_user_role'), ['user_id', 'role_id'])

    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_suites_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('test_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_plans_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('test_daily_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_daily_snapshots_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('test_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_request', sa.VARCHAR(length=30), server_default=sa.text("('')"), nullable=True))
        batch_op.add_column(sa.Column('deployment_batch', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=True))
        batch_op.add_column(sa.Column('release_train', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_cases_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_test_cases_suite_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_requirement_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_team_members_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sprints_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('scope_change_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_scr_program_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_scope_change_requests_program_id'))
        batch_op.drop_index('idx_scr_program_status')
        batch_op.create_unique_constraint(batch_op.f('uq_scr_project_code'), ['project_id', 'code'])
        batch_op.create_index(batch_op.f('idx_scr_project_status'), ['project_id', 'status'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('scope_change_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_scope_change_logs_program_id'))
        batch_op.drop_index('idx_scl_program')
        batch_op.create_index(batch_op.f('idx_scl_project'), ['project_id'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scenarios_project_id'))

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_risks_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_requirements_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('requirement_open_item_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_roil_tenant_program_project')
        batch_op.drop_index(batch_op.f('ix_requirement_open_item_links_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_open_item_links_program_id'))

    with op.batch_alter_table('requirement_dependencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requirement_dependencies_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_dependencies_program_id'))
        batch_op.drop_index('ix_rdep_tenant_program_project')

    with op.batch_alter_table('raci_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_raci_entries_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index('ix_raci_entry_tenant_project')
        batch_op.drop_index('ix_raci_entry_project_activity')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('raci_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_raci_activities_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index('ix_raci_activity_tenant_project')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('project_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_prole_program_user_role_area', type_='unique')
        batch_op.drop_index(batch_op.f('ix_project_roles_program_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_prole_project_user_role_area'), ['project_id', 'user_id', 'role', 'process_area'])
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('process_variant_imports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_process_variant_imports_program_id'))
        batch_op.drop_index('idx_pvi_tenant_program')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_ps_tenant_program_project')
        batch_op.drop_index(batch_op.f('ix_process_steps_project_id'))
        batch_op.drop_index(batch_op.f('ix_process_steps_program_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('process_levels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_pl_program_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_process_levels_program_id'))
        batch_op.drop_index('idx_pl_program_scope_item')
        batch_op.drop_index('idx_pl_program_parent')
        batch_op.drop_index('idx_pl_program_level')
        batch_op.create_unique_constraint(batch_op.f('uq_pl_project_code'), ['project_id', 'code'])
        batch_op.create_index(batch_op.f('idx_pl_scope_item'), ['project_id', 'scope_item_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_pl_project_scope_item'), ['project_id', 'scope_item_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_pl_project_parent'), ['project_id', 'parent_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pl_project_level'), ['project_id', 'level'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('post_golive_change_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_post_golive_change_requests_project_id'))
        batch_op.drop_index('ix_pgcr_tenant_project')

    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_phases_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('phase_gates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_phase_gates_program_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('open_item_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_open_item_comments_project_id'))
        batch_op.drop_index(batch_op.f('ix_open_item_comments_program_id'))
        batch_op.drop_index('ix_oic_tenant_program_project')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_issues_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_interfaces_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('ix_interfaces_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('hypercare_incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'hypercare_war_rooms', ['war_room_id'], ['id'])

    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('explore_workshops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_ews_program_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_explore_workshops_program_id'))
        batch_op.drop_index('idx_ews_program_status')
        batch_op.drop_index('idx_ews_program_date')
        batch_op.drop_index('idx_ews_program_area')
        batch_op.create_unique_constraint(batch_op.f('uq_ews_project_code'), ['project_id', 'code'])
        batch_op.create_index(batch_op.f('idx_ews_project_status'), ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_ews_project_date'), ['project_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_ews_project_area'), ['project_id', 'process_area'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('explore_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_class', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.VARCHAR(length=24), nullable=True))
        batch_op.add_column(sa.Column('trigger_reason', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('delivery_pattern', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_ereq_program_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_explore_requirements_program_id'))
        batch_op.drop_index('idx_ereq_program_status')
        batch_op.drop_index('idx_ereq_program_priority')
        batch_op.drop_index('idx_ereq_program_area')
        batch_op.create_unique_constraint(batch_op.f('uq_ereq_project_code'), ['project_id', 'code'])
        batch_op.create_index(batch_op.f('ix_ereq_trigger_reason'), ['trigger_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_ereq_requirement_class'), ['requirement_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_ereq_delivery_status'), ['delivery_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ereq_delivery_pattern'), ['delivery_pattern'], unique=False)
        batch_op.create_index(batch_op.f('idx_ereq_project_status'), ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_ereq_project_priority'), ['project_id', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_ereq_project_area'), ['project_id', 'process_area'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('explore_open_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_eoi_program_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_explore_open_items_program_id'))
        batch_op.drop_index('idx_eoi_program_status')
        batch_op.create_unique_constraint(batch_op.f('uq_eoi_project_code'), ['project_id', 'code'])
        batch_op.create_index(batch_op.f('idx_eoi_project_status'), ['project_id', 'status'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('explore_decisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_explore_decisions_program_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_defects_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_defects_linked_requirement_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_decisions_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cutover_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cutover_plans_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_config_items_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_committees_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('backlog_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_backlog_items_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_project_id'))
        batch_op.drop_index('idx_audit_project')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'programs', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_attachments_program_id'))
        batch_op.drop_index('idx_att_program')
        batch_op.create_index(batch_op.f('idx_att_project'), ['project_id'], unique=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_approval_workflows_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_actions_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###

