"""workshop_documents table

Revision ID: c75811018b4d
Revises: 25890e807851
Create Date: 2026-02-09 14:53:33.246171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75811018b4d'
down_revision = '25890e807851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False, comment='Original upload filename'),
    sa.Column('file_type', sa.String(length=30), nullable=True, comment='pdf | docx | xlsx | pptx | image | other'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Size in bytes'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Server-side storage path'),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_documents')
    # ### end Alembic commands ###
