"""add requirement_id FK to scope_items

Revision ID: d1a4e571c168
Revises: e5a2b9c4d701
Create Date: 2026-02-09 12:29:17.537953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a4e571c168'
down_revision = 'e5a2b9c4d701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_id', sa.Integer(), nullable=True, comment='Linked requirement for single-source-of-truth traceability'))
        batch_op.create_foreign_key('fk_scope_items_requirement_id', 'requirements', ['requirement_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scope_items_requirement_id', type_='foreignkey')
        batch_op.drop_column('requirement_id')

    # ### end Alembic commands ###
